<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Alumno;

class AlumnoSeeder extends Seeder
{
    public function run(): void
    {
        $alumnos = [
            [
                'numero_zonificacion' => '101',
                'anio_egreso' => '2020-07-15',
                'talla_camisa' => 40,
                'talla_pantalon' => 38,
                'talla_zapato' => 41,
                'peso' => 62,
                'estatura' => 168,
                'orden_nacimiento_id' => 1,
                'institucion_procedencia_id' => 1,
                'expresion_literaria_id' => 1,
                'lateralidad_id' => 1,
                'persona_id' => 1,
                'status' => 'Activo',
            ],
            [
                'numero_zonificacion' => '102',
                'anio_egreso' => '2019-07-10',
                'talla_camisa' => 42,
                'talla_pantalon' => 40,
                'talla_zapato' => 43,
                'peso' => 70,
                'estatura' => 175,
                'orden_nacimiento_id' => 2,
                'institucion_procedencia_id' => 2,
                'expresion_literaria_id' => 2,
                'lateralidad_id' => 2,
                'persona_id' => 2,
                'status' => 'Activo',
            ],
            [
                'numero_zonificacion' => '103',
                'anio_egreso' => '2021-08-01',
                'talla_camisa' => 38,
                'talla_pantalon' => 36,
                'talla_zapato' => 40,
                'peso' => 58,
                'estatura' => 160,
                'orden_nacimiento_id' => 3,
                'institucion_procedencia_id' => 3,
                'expresion_literaria_id' => 3,
                'lateralidad_id' => 1,
                'persona_id' => 3,
                'status' => 'Activo',
            ],
            [
                'numero_zonificacion' => '104',
                'anio_egreso' => '2019-07-22',
                'talla_camisa' => 44,
                'talla_pantalon' => 42,
                'talla_zapato' => 44,
                'peso' => 78,
                'estatura' => 182,
                'orden_nacimiento_id' => 1,
                'institucion_procedencia_id' => 1,
                'expresion_literaria_id' => 2,
                'lateralidad_id' => 2,
                'persona_id' => 4,
                'status' => 'Activo',
            ],
            [
                'numero_zonificacion' => '105',
                'anio_egreso' => '2022-06-30',
                'talla_camisa' => 39,
                'talla_pantalon' => 38,
                'talla_zapato' => 41,
                'peso' => 60,
                'estatura' => 165,
                'orden_nacimiento_id' => 2,
                'institucion_procedencia_id' => 3,
                'expresion_literaria_id' => 1,
                'lateralidad_id' => 1,
                'persona_id' => 5,
                'status' => 'Activo',
            ],
            [
                'numero_zonificacion' => '106',
                'anio_egreso' => '2020-07-11',
                'talla_camisa' => 41,
                'talla_pantalon' => 39,
                'talla_zapato' => 42,
                'peso' => 66,
                'estatura' => 170,
                'orden_nacimiento_id' => 1,
                'institucion_procedencia_id' => 2,
                'expresion_literaria_id' => 3,
                'lateralidad_id' => 2,
                'persona_id' => 6,
                'status' => 'Activo',
            ],
            [
                'numero_zonificacion' => '107',
                'anio_egreso' => '2018-07-20',
                'talla_camisa' => 43,
                'talla_pantalon' => 42,
                'talla_zapato' => 44,
                'peso' => 80,
                'estatura' => 185,
                'orden_nacimiento_id' => 3,
                'institucion_procedencia_id' => 1,
                'expresion_literaria_id' => 2,
                'lateralidad_id' => 1,
                'persona_id' => 7,
                'status' => 'Activo',
            ],
            [
                'numero_zonificacion' => '108',
                'anio_egreso' => '2021-03-05',
                'talla_camisa' => 37,
                'talla_pantalon' => 36,
                'talla_zapato' => 38,
                'peso' => 52,
                'estatura' => 155,
                'orden_nacimiento_id' => 2,
                'institucion_procedencia_id' => 2,
                'expresion_literaria_id' => 1,
                'lateralidad_id' => 2,
                'persona_id' => 8,
                'status' => 'Activo',
            ],
            [
                'numero_zonificacion' => '109',
                'anio_egreso' => '2019-11-12',
                'talla_camisa' => 40,
                'talla_pantalon' => 38,
                'talla_zapato' => 41,
                'peso' => 64,
                'estatura' => 170,
                'orden_nacimiento_id' => 1,
                'institucion_procedencia_id' => 3,
                'expresion_literaria_id' => 3,
                'lateralidad_id' => 1,
                'persona_id' => 9,
                'status' => 'Activo',
            ],
            [
                'numero_zonificacion' => '110',
                'anio_egreso' => '2020-10-01',
                'talla_camisa' => 42,
                'talla_pantalon' => 40,
                'talla_zapato' => 43,
                'peso' => 72,
                'estatura' => 178,
                'orden_nacimiento_id' => 3,
                'institucion_procedencia_id' => 1,
                'expresion_literaria_id' => 2,
                'lateralidad_id' => 2,
                'persona_id' => 10,
                'status' => 'Activo',
            ],
        ];

        foreach ($alumnos as $alumno) {
            Alumno::create($alumno);
        }

        $this->command->info('Seeder de 10 alumnos ejecutado correctamente.');
    }
}
