<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class LocalidadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        $localidades = [
            [ 'municipio_id' => 1, 'nombre_localidad' => 'Alto Orinoco'],
            [ 'municipio_id' => 1, 'nombre_localidad' => 'Huachamacare Acanaña'],
            [ 'municipio_id' => 1, 'nombre_localidad' => 'Marawaka Toky Shamanaña'],
            [ 'municipio_id' => 1, 'nombre_localidad' => 'Mavaka Mavaka'],
            [ 'municipio_id' => 1, 'nombre_localidad' => 'Sierra Parima Parimabé'],
            [ 'municipio_id' => 2, 'nombre_localidad' => 'Ucata Laja Lisa'],
            [ 'municipio_id' => 2, 'nombre_localidad' => 'Yapacana Macuruco'],
            [ 'municipio_id' => 2, 'nombre_localidad' => 'Caname Guarinuma'],
            [ 'municipio_id' => 3, 'nombre_localidad' => 'Fernando Girón Tovar'],
            [ 'municipio_id' => 3, 'nombre_localidad' => 'Luis Alberto Gómez'],
            [ 'municipio_id' => 3, 'nombre_localidad' => 'Pahueña Limón de Parhueña'],
            [ 'municipio_id' => 3, 'nombre_localidad' => 'Platanillal Platanillal'],
            [ 'municipio_id' => 4, 'nombre_localidad' => 'Samariapo'],
            [ 'municipio_id' => 4, 'nombre_localidad' => 'Sipapo'],
            [ 'municipio_id' => 4, 'nombre_localidad' => 'Munduapo'],
            [ 'municipio_id' => 4, 'nombre_localidad' => 'Guayapo'],
            [ 'municipio_id' => 5, 'nombre_localidad' => 'Alto Ventuari'],
            [ 'municipio_id' => 5, 'nombre_localidad' => 'Medio Ventuari'],
            [ 'municipio_id' => 5, 'nombre_localidad' => 'Bajo Ventuari'],
            [ 'municipio_id' => 6, 'nombre_localidad' => 'Victorino'],
            [ 'municipio_id' => 6, 'nombre_localidad' => 'Comunidad'],
            [ 'municipio_id' => 7, 'nombre_localidad' => 'Casiquiare'],
            [ 'municipio_id' => 7, 'nombre_localidad' => 'Cocuy'],
            [ 'municipio_id' => 7, 'nombre_localidad' => 'San Carlos de Río Negro'],
            [ 'municipio_id' => 7, 'nombre_localidad' => 'Solano'],
            [ 'municipio_id' => 8, 'nombre_localidad' => 'Anaco'],
            [ 'municipio_id' => 8, 'nombre_localidad' => 'San Joaquín'],
            [ 'municipio_id' => 9, 'nombre_localidad' => 'Cachipo'],
            [ 'municipio_id' => 9, 'nombre_localidad' => 'Aragua de Barcelona'],
            [ 'municipio_id' => 11, 'nombre_localidad' => 'Lechería'],
            [ 'municipio_id' => 11, 'nombre_localidad' => 'El Morro'],
            [ 'municipio_id' => 12, 'nombre_localidad' => 'Puerto Píritu'],
            [ 'municipio_id' => 12, 'nombre_localidad' => 'San Miguel'],
            [ 'municipio_id' => 12, 'nombre_localidad' => 'Sucre'],
            [ 'municipio_id' => 13, 'nombre_localidad' => 'Valle de Guanape'],
            [ 'municipio_id' => 13, 'nombre_localidad' => 'Santa Bárbara'],
            [ 'municipio_id' => 14, 'nombre_localidad' => 'El Chaparro'],
            [ 'municipio_id' => 14, 'nombre_localidad' => 'Tomás Alfaro'],
            [ 'municipio_id' => 14, 'nombre_localidad' => 'Calatrava'],
            [ 'municipio_id' => 15, 'nombre_localidad' => 'Guanta'],
            [ 'municipio_id' => 15, 'nombre_localidad' => 'Chorrerón'],
            [ 'municipio_id' => 16, 'nombre_localidad' => 'Mamo'],
            [ 'municipio_id' => 16, 'nombre_localidad' => 'Soledad'],
            ['municipio_id' => 17, 'nombre_localidad' => 'Mapire'],
            ['municipio_id' => 17, 'nombre_localidad' => 'Piar'],
            ['municipio_id' => 17, 'nombre_localidad' => 'Santa Clara'],
            ['municipio_id' => 17, 'nombre_localidad' => 'San Diego de Cabrutica'],
            ['municipio_id' => 17, 'nombre_localidad' => 'Uverito'],
            ['municipio_id' => 17, 'nombre_localidad' => 'Zuata'],
            ['municipio_id' => 18, 'nombre_localidad' => 'Puerto La Cruz'],
            ['municipio_id' => 18, 'nombre_localidad' => 'Pozuelos'],
            ['municipio_id' => 19, 'nombre_localidad' => 'Onoto'],
            ['municipio_id' => 19, 'nombre_localidad' => 'San Pablo'],
            ['municipio_id' => 20, 'nombre_localidad' => 'San Mateo'],
            ['municipio_id' => 20, 'nombre_localidad' => 'El Carito'],
            ['municipio_id' => 20, 'nombre_localidad' => 'Santa Inés'],
            ['municipio_id' => 20, 'nombre_localidad' => 'La Romereña'],
            ['municipio_id' => 21, 'nombre_localidad' => 'Atapirire'],
            ['municipio_id' => 21, 'nombre_localidad' => 'Boca del Pao'],
            ['municipio_id' => 21, 'nombre_localidad' => 'El Pao'],
            ['municipio_id' => 21, 'nombre_localidad' => 'Pariaguán'],
            ['municipio_id' => 22, 'nombre_localidad' => 'Cantaura'],
            ['municipio_id' => 22, 'nombre_localidad' => 'Libertador'],
            ['municipio_id' => 22, 'nombre_localidad' => 'Santa Rosa'],
            ['municipio_id' => 22, 'nombre_localidad' => 'Urica'],
            ['municipio_id' => 23, 'nombre_localidad' => 'Píritu'],
            ['municipio_id' => 23, 'nombre_localidad' => 'San Francisco'],
            ['municipio_id' => 24, 'nombre_localidad' => 'San José de Guanipa'],
            ['municipio_id' => 25, 'nombre_localidad' => 'Boca de Uchire'],
            ['municipio_id' => 25, 'nombre_localidad' => 'Boca de Chávez'],
            ['municipio_id' => 26, 'nombre_localidad' => 'Pueblo Nuevo'],
            ['municipio_id' => 26, 'nombre_localidad' => 'Santa Ana'],
            ['municipio_id' => 27, 'nombre_localidad' => 'Bergantín'],
            ['municipio_id' => 27, 'nombre_localidad' => 'Caigua'],
            ['municipio_id' => 27, 'nombre_localidad' => 'El Carmen'],
            ['municipio_id' => 27, 'nombre_localidad' => 'El Pilar'],
            ['municipio_id' => 27, 'nombre_localidad' => 'Naricual'],
            ['municipio_id' => 27, 'nombre_localidad' => 'San Crsitóbal'],
            ['municipio_id' => 28, 'nombre_localidad' => 'Edmundo Barrios'],
            ['municipio_id' => 28, 'nombre_localidad' => 'Miguel Otero Silva'],
            ['municipio_id' => 29, 'nombre_localidad' => 'Achaguas'],
            ['municipio_id' => 29, 'nombre_localidad' => 'Apurito'],
            ['municipio_id' => 29, 'nombre_localidad' => 'El Yagual'],
            ['municipio_id' => 29, 'nombre_localidad' => 'Guachara'],
            ['municipio_id' => 29, 'nombre_localidad' => 'Mucuritas'],
            ['municipio_id' => 29, 'nombre_localidad' => 'Queseras del medio'],
            ['municipio_id' => 30, 'nombre_localidad' => 'Biruaca'],
            ['municipio_id' => 31, 'nombre_localidad' => 'Bruzual'],
            ['municipio_id' => 31, 'nombre_localidad' => 'Mantecal'],
            ['municipio_id' => 31, 'nombre_localidad' => 'Quintero'],
            ['municipio_id' => 31, 'nombre_localidad' => 'Rincón Hondo'],
            ['municipio_id' => 31, 'nombre_localidad' => 'San Vicente'],
            ['municipio_id' => 32, 'nombre_localidad' => 'Guasdualito'],
            ['municipio_id' => 32, 'nombre_localidad' => 'Aramendi'],
            ['municipio_id' => 32, 'nombre_localidad' => 'El Amparo'],
            ['municipio_id' => 32, 'nombre_localidad' => 'San Camilo'],
            ['municipio_id' => 32, 'nombre_localidad' => 'Urdaneta'],
            ['municipio_id' => 33, 'nombre_localidad' => 'San Juan de Payara'],
            ['municipio_id' => 33, 'nombre_localidad' => 'Codazzi'],
            [ 'municipio_id' => 33, 'nombre_localidad' => 'Cunaviche'],
            [ 'municipio_id' => 34, 'nombre_localidad' => 'Elorza'],
            [ 'municipio_id' => 34, 'nombre_localidad' => 'La Trinidad'],
            [ 'municipio_id' => 35, 'nombre_localidad' => 'San Fernando'],
            [ 'municipio_id' => 35, 'nombre_localidad' => 'El Recreo'],
            [ 'municipio_id' => 35, 'nombre_localidad' => 'Peñalver'],
            [ 'municipio_id' => 35, 'nombre_localidad' => 'San Rafael de Atamaica'],
            [ 'municipio_id' => 36, 'nombre_localidad' => 'Pedro José Ovalles'],
            [ 'municipio_id' => 36, 'nombre_localidad' => 'Joaquín Crespo'],
            [ 'municipio_id' => 36, 'nombre_localidad' => 'José Casanova Godoy'],
            [ 'municipio_id' => 36, 'nombre_localidad' => 'Madre María de San José'],
            [ 'municipio_id' => 36, 'nombre_localidad' => 'Andrés Eloy Blanco'],
            [ 'municipio_id' => 36, 'nombre_localidad' => 'Los Tacarigua'],
            [ 'municipio_id' => 36, 'nombre_localidad' => 'Las Delicias'],
            [ 'municipio_id' => 36, 'nombre_localidad' => 'Choroní'],
            [ 'municipio_id' => 37, 'nombre_localidad' => 'Bolívar'],
            [ 'municipio_id' => 38, 'nombre_localidad' => 'Camatagua'],
            [ 'municipio_id' => 38, 'nombre_localidad' => 'Carmen de Cura'],
            [ 'municipio_id' => 39, 'nombre_localidad' => 'Santa Rita'],
            [ 'municipio_id' => 39, 'nombre_localidad' => 'Francisco de Miranda'],
            [ 'municipio_id' => 39, 'nombre_localidad' => 'Moseñor Feliciano González'],
            [ 'municipio_id' => 40, 'nombre_localidad' => 'Santa Cruz'],
            [ 'municipio_id' => 41, 'nombre_localidad' => 'José Félix Ribas'],
            [ 'municipio_id' => 41, 'nombre_localidad' => 'Castor Nieves Ríos'],
            [ 'municipio_id' => 41, 'nombre_localidad' => 'Las Guacamayas'],
            [ 'municipio_id' => 41, 'nombre_localidad' => 'Pao de Zárate'],
            [ 'municipio_id' => 41, 'nombre_localidad' => 'Zuata'],
            [ 'municipio_id' => 42, 'nombre_localidad' => 'José Rafael Revenga'],
            [ 'municipio_id' => 43, 'nombre_localidad' => 'Palo Negro'],
            [ 'municipio_id' => 43, 'nombre_localidad' => 'San Martín de Porres'],
            [ 'municipio_id' => 44, 'nombre_localidad' => 'El Limón'],
            [ 'municipio_id' => 44, 'nombre_localidad' => 'Caña de Azúcar'],
            [ 'municipio_id' => 45, 'nombre_localidad' => 'Ocumare de la Costa'],
            [ 'municipio_id' => 46, 'nombre_localidad' => 'San Casimiro'],
            [ 'municipio_id' => 46, 'nombre_localidad' => 'Güiripa'],
            [ 'municipio_id' => 46, 'nombre_localidad' => 'Ollas de Caramacate'],
            [ 'municipio_id' => 46, 'nombre_localidad' => 'Valle Morín'],
            [ 'municipio_id' => 47, 'nombre_localidad' => 'San Sebastían'],
            [ 'municipio_id' => 48, 'nombre_localidad' => 'Turmero'],
            [ 'municipio_id' => 48, 'nombre_localidad' => 'Arevalo Aponte'],
            [ 'municipio_id' => 48, 'nombre_localidad' => 'Chuao'],
            [ 'municipio_id' => 48, 'nombre_localidad' => 'Samán de Güere'],
             [ 'municipio_id' => 48, 'nombre_localidad' => 'Alfredo Pacheco Miranda'],
            [ 'municipio_id' => 49, 'nombre_localidad' => 'Santos Michelena'],
            [ 'municipio_id' => 49, 'nombre_localidad' => 'Tiara'],
            [ 'municipio_id' => 50, 'nombre_localidad' => 'Cagua'],
            [ 'municipio_id' => 50, 'nombre_localidad' => 'Bella Vista'],
            [ 'municipio_id' => 51, 'nombre_localidad' => 'Tovar'],
            [ 'municipio_id' => 52, 'nombre_localidad' => 'Urdaneta'],
            [ 'municipio_id' => 52, 'nombre_localidad' => 'Las Peñitas'],
            [ 'municipio_id' => 52, 'nombre_localidad' => 'San Francisco de Cara'],
            [ 'municipio_id' => 52, 'nombre_localidad' => 'Taguay'],
            [ 'municipio_id' => 53, 'nombre_localidad' => 'Zamora'],
            [ 'municipio_id' => 53, 'nombre_localidad' => 'Magdaleno'],
            [ 'municipio_id' => 53, 'nombre_localidad' => 'San Francisco de Asís'],
            [ 'municipio_id' => 53, 'nombre_localidad' => 'Valles de Tucutunemo'],
            [ 'municipio_id' => 53, 'nombre_localidad' => 'Augusto Mijares'],
            [ 'municipio_id' => 54, 'nombre_localidad' => 'Sabaneta'],
            [ 'municipio_id' => 54, 'nombre_localidad' => 'Juan Antonio Rodríguez Domínguez'],
            [ 'municipio_id' => 55, 'nombre_localidad' => 'El Cantón'],
            [ 'municipio_id' => 55, 'nombre_localidad' => 'Santa Cruz de Guacas'],
            [ 'municipio_id' => 55, 'nombre_localidad' => 'Puerto Vivas'],
            [ 'municipio_id' => 56, 'nombre_localidad' => 'Ticoporo'],
            [ 'municipio_id' => 56, 'nombre_localidad' => 'Nicolás Pulido'],
            [ 'municipio_id' => 56, 'nombre_localidad' => 'Andrés Bello'],
            [ 'municipio_id' => 57, 'nombre_localidad' => 'Arismendi'],
            [ 'municipio_id' => 57, 'nombre_localidad' => 'Guadarrama'],
            [ 'municipio_id' => 57, 'nombre_localidad' => 'La Unión'],
            [ 'municipio_id' => 57, 'nombre_localidad' => 'San Antonio'],
            [ 'municipio_id' => 58, 'nombre_localidad' => 'Barinas'],
            [ 'municipio_id' => 58, 'nombre_localidad' => 'Alberto Arvelo Larriva'],
            [ 'municipio_id' => 58, 'nombre_localidad' => 'San Silvestre'],
            [ 'municipio_id' => 58, 'nombre_localidad' => 'Santa Inés'],
            [ 'municipio_id' => 58, 'nombre_localidad' => 'Santa Lucía'],
            [ 'municipio_id' => 58, 'nombre_localidad' => 'Torumos'],
            [ 'municipio_id' => 58, 'nombre_localidad' => 'El Carmen'],
            [ 'municipio_id' => 58, 'nombre_localidad' => 'Rómulo Betancourt'],
            [ 'municipio_id' => 58, 'nombre_localidad' => 'Corazón de Jesús'],
            [ 'municipio_id' => 58, 'nombre_localidad' => 'Ramón Ignacio Méndez'],
            [ 'municipio_id' => 58, 'nombre_localidad' => 'Alto Barinas'],
            [ 'municipio_id' => 58, 'nombre_localidad' => 'Manuel Palacio Fajardo'],
            [ 'municipio_id' => 58, 'nombre_localidad' => 'Juan Antonio Rodríguez Domínguez'],
            [ 'municipio_id' => 58, 'nombre_localidad' => 'Dominga Ortiz de Páez'],
            [ 'municipio_id' => 59, 'nombre_localidad' => 'Barinitas'],
            [ 'municipio_id' => 59, 'nombre_localidad' => 'Altamira de Cáceres'],
            [ 'municipio_id' => 59, 'nombre_localidad' => 'Calderas'],
            [ 'municipio_id' => 60, 'nombre_localidad' => 'Barrancas'],
            [ 'municipio_id' => 60, 'nombre_localidad' => 'El Socorro'],
            [ 'municipio_id' => 60, 'nombre_localidad' => 'Mazparrito'],
            [ 'municipio_id' => 61, 'nombre_localidad' => 'Santa Bárbara'],
            [ 'municipio_id' => 61, 'nombre_localidad' => 'Pedro Briceño Méndez'],
            [ 'municipio_id' => 61, 'nombre_localidad' => 'Ramón Ignacio Méndez'],
            [ 'municipio_id' => 61, 'nombre_localidad' => 'José Ignacio del Pumar'],
            [ 'municipio_id' => 62, 'nombre_localidad' => 'Obispos'],
            [ 'municipio_id' => 62, 'nombre_localidad' => 'Los Guasimitos'],
            [ 'municipio_id' => 62, 'nombre_localidad' => 'El Real'],
            [ 'municipio_id' => 62, 'nombre_localidad' => 'La Luz'],
            [ 'municipio_id' => 63, 'nombre_localidad' => 'Ciudad Bolívia'],
            [ 'municipio_id' => 63, 'nombre_localidad' => 'José Ignacio Briceño'],
            [ 'municipio_id' => 63, 'nombre_localidad' => 'José Félix Ribas'],
            [ 'municipio_id' => 63, 'nombre_localidad' => 'Páez'],
            [ 'municipio_id' => 64, 'nombre_localidad' => 'Libertad'],
            [ 'municipio_id' => 64, 'nombre_localidad' => 'Dolores'],
            [ 'municipio_id' => 64, 'nombre_localidad' => 'Santa Rosa'],
            [ 'municipio_id' => 64, 'nombre_localidad' => 'Palacio Fajardo'],
            [ 'municipio_id' => 65, 'nombre_localidad' => 'Ciudad de Nutrias'],
            [ 'municipio_id' => 65, 'nombre_localidad' => 'El Regalo'],
            [ 'municipio_id' => 65, 'nombre_localidad' => 'Puerto Nutrias'],
            [ 'municipio_id' => 65, 'nombre_localidad' => 'Santa Catalina'],
            [ 'municipio_id' => 66, 'nombre_localidad' => 'Cachamay'],
            [ 'municipio_id' => 66, 'nombre_localidad' => 'Chirica'],
            [ 'municipio_id' => 66, 'nombre_localidad' => 'Dalla Costa'],
            [ 'municipio_id' => 66, 'nombre_localidad' => 'Once de Abril'],
            [ 'municipio_id' => 66, 'nombre_localidad' => 'Simón Bolívar'],
            [ 'municipio_id' => 66, 'nombre_localidad' => 'Unare'],
            [ 'municipio_id' => 66, 'nombre_localidad' => 'Universidad'],
            [ 'municipio_id' => 66, 'nombre_localidad' => 'Vista al Sol'],
            [ 'municipio_id' => 66, 'nombre_localidad' => 'Pozo Verde'],
            [ 'municipio_id' => 66, 'nombre_localidad' => 'Yocoima'],
            [ 'municipio_id' => 66, 'nombre_localidad' => '5 de Julio'],
            [ 'municipio_id' => 67, 'nombre_localidad' => 'Cedeño'],
            [ 'municipio_id' => 67, 'nombre_localidad' => 'Altagracia'],
            [ 'municipio_id' => 67, 'nombre_localidad' => 'Ascensión Farreras'],
            [ 'municipio_id' => 67, 'nombre_localidad' => 'Guaniamo'],
            [ 'municipio_id' => 67, 'nombre_localidad' => 'La Urbana'],
            [ 'municipio_id' => 67, 'nombre_localidad' => 'Pijiguaos'],
            [ 'municipio_id' => 68, 'nombre_localidad' => 'El Callao'],
            [ 'municipio_id' => 69, 'nombre_localidad' => 'Gran Sabana'],
            [ 'municipio_id' => 69, 'nombre_localidad' => 'Ikabarú'],
            [ 'municipio_id' => 70, 'nombre_localidad' => 'Catedral'],
            [ 'municipio_id' => 70, 'nombre_localidad' => 'Zea'],
            [ 'municipio_id' => 70, 'nombre_localidad' => 'Orinoco'],
            [ 'municipio_id' => 70, 'nombre_localidad' => 'José Antonio Páez'],
            [ 'municipio_id' => 70, 'nombre_localidad' => 'Marhuanta'],
            [ 'municipio_id' => 70, 'nombre_localidad' => 'Agua Salada'],
            [ 'municipio_id' => 70, 'nombre_localidad' => 'Vista Hermosa'],
            [ 'municipio_id' => 70, 'nombre_localidad' => 'La Sabanita'],
            [ 'municipio_id' => 70, 'nombre_localidad' => 'Panapana'],
            [ 'municipio_id' => 71, 'nombre_localidad' => 'Andrés Eloy Blanco'],
            [ 'municipio_id' => 71, 'nombre_localidad' => 'Pedro Cova'],
            [ 'municipio_id' => 72, 'nombre_localidad' => 'Raúl Leoni'],
            [ 'municipio_id' => 72, 'nombre_localidad' => 'Barceloneta'],
            [ 'municipio_id' => 72, 'nombre_localidad' => 'Santa Bárbara'],
            [ 'municipio_id' => 72, 'nombre_localidad' => 'San Francisco'],
            [ 'municipio_id' => 73, 'nombre_localidad' => 'Roscio'],
            [ 'municipio_id' => 73, 'nombre_localidad' => 'Salóm'],
            [ 'municipio_id' => 74, 'nombre_localidad' => 'Sifontes'],
            [ 'municipio_id' => 74, 'nombre_localidad' => 'Dalla Costa'],
            [ 'municipio_id' => 74, 'nombre_localidad' => 'San Isidro'],
            [ 'municipio_id' => 75, 'nombre_localidad' => 'Sucre'],
            [ 'municipio_id' => 75, 'nombre_localidad' => 'Aripao'],
            [ 'municipio_id' => 75, 'nombre_localidad' => 'Guarataro'],
            [ 'municipio_id' => 75, 'nombre_localidad' => 'Las Majadas'],
            [ 'municipio_id' => 75, 'nombre_localidad' => 'Moitaco'],
            [ 'municipio_id' => 76, 'nombre_localidad' => 'Padre Pedro Chien'],
            [ 'municipio_id' => 76, 'nombre_localidad' => 'Río Grande'],
            [ 'municipio_id' => 77, 'nombre_localidad' => 'Bejuma'],
            [ 'municipio_id' => 77, 'nombre_localidad' => 'Canoabo'],
            [ 'municipio_id' => 77, 'nombre_localidad' => 'Simón Bolívar'],
            [ 'municipio_id' => 78, 'nombre_localidad' => 'Güigüe'],
            [ 'municipio_id' => 78, 'nombre_localidad' => 'Carabobo'],
            [ 'municipio_id' => 78, 'nombre_localidad' => 'Tacarigua'],
            [ 'municipio_id' => 79, 'nombre_localidad' => 'Mariara'],
            [ 'municipio_id' => 79, 'nombre_localidad' => 'Aguas Calientes'],
            [ 'municipio_id' => 80, 'nombre_localidad' => 'Ciudad Alianza'],
            [ 'municipio_id' => 80, 'nombre_localidad' => 'Guacara'],
            [ 'municipio_id' => 80, 'nombre_localidad' => 'Yagua'],
            [ 'municipio_id' => 81, 'nombre_localidad' => 'Morón'],
            [ 'municipio_id' => 81, 'nombre_localidad' => 'Yagua'],
            [ 'municipio_id' => 82, 'nombre_localidad' => 'Tocuyito'],
            [ 'municipio_id' => 82, 'nombre_localidad' => 'Independencia'],
            [ 'municipio_id' => 83, 'nombre_localidad' => 'Los Guayos'],
            [ 'municipio_id' => 84, 'nombre_localidad' => 'Miranda'],
            [ 'municipio_id' => 85, 'nombre_localidad' => 'Montalbán'],
            [ 'municipio_id' => 86, 'nombre_localidad' => 'Naguanagua'],
            [ 'municipio_id' => 87, 'nombre_localidad' => 'Bartolomé Salóm'],
            [ 'municipio_id' => 87, 'nombre_localidad' => 'Democracia'],
            [ 'municipio_id' => 87, 'nombre_localidad' => 'Fraternidad'],
            [ 'municipio_id' => 87, 'nombre_localidad' => 'Goaigoaza'],
            [ 'municipio_id' => 87, 'nombre_localidad' => 'Juan José Flores'],
            [ 'municipio_id' => 87, 'nombre_localidad' => 'Unión'],
            [ 'municipio_id' => 87, 'nombre_localidad' => 'Borburata'],
            [ 'municipio_id' => 87, 'nombre_localidad' => 'Patanemo'],
            [ 'municipio_id' => 88, 'nombre_localidad' => 'San Diego'],
            [ 'municipio_id' => 89, 'nombre_localidad' => 'San Joaquín'],
            [ 'municipio_id' => 90, 'nombre_localidad' => 'Candelaria'],
            [ 'municipio_id' => 90, 'nombre_localidad' => 'Catedral'],
            [ 'municipio_id' => 90, 'nombre_localidad' => 'El Socorro'],
            [ 'municipio_id' => 90, 'nombre_localidad' => 'Miguel Peña'],
            [ 'municipio_id' => 90, 'nombre_localidad' => 'Rafael Urdaneta'],
            [ 'municipio_id' => 90, 'nombre_localidad' => 'San Blas'],
            [ 'municipio_id' => 90, 'nombre_localidad' => 'San José'],
            [ 'municipio_id' => 90, 'nombre_localidad' => 'Santa Rosa'],
            [ 'municipio_id' => 90, 'nombre_localidad' => 'Negro Primero'],
            [ 'municipio_id' => 91, 'nombre_localidad' => 'Cojedes'],
            [ 'municipio_id' => 91, 'nombre_localidad' => 'Juan de Mata Suárez'],
            [ 'municipio_id' => 92, 'nombre_localidad' => 'Tinaquillo'],
            [ 'municipio_id' => 93, 'nombre_localidad' => 'El Baúl'],
            [ 'municipio_id' => 93, 'nombre_localidad' => 'Sucre'],
            [ 'municipio_id' => 94, 'nombre_localidad' => 'La Aguadita'],
            [ 'municipio_id' => 94, 'nombre_localidad' => 'Macapo'],
            [ 'municipio_id' => 95, 'nombre_localidad' => 'El Pao'],
            [ 'municipio_id' => 96, 'nombre_localidad' => 'El Amparo'],
            [ 'municipio_id' => 96, 'nombre_localidad' => 'Libertad de Cojedes'],
            [ 'municipio_id' => 97, 'nombre_localidad' => 'Rómulo Gallegos'],
            [ 'municipio_id' => 98, 'nombre_localidad' => 'San Carlos de Austria'],
            [ 'municipio_id' => 98, 'nombre_localidad' => 'Juan Ángel Bravo'],
            [ 'municipio_id' => 98, 'nombre_localidad' => 'Manuel Manrique'],
            [ 'municipio_id' => 99, 'nombre_localidad' => 'General en Jefe José Laurencio Silva'],
            [ 'municipio_id' => 100, 'nombre_localidad' => 'Curiapo'],
            [ 'municipio_id' => 100, 'nombre_localidad' => 'Almirante Luis Brión'],
            [ 'municipio_id' => 100, 'nombre_localidad' => 'Francisco Aniceto Lugo'],
            [ 'municipio_id' => 100, 'nombre_localidad' => 'Manuel Renaud'],
            [ 'municipio_id' => 100, 'nombre_localidad' => 'Padre Barral'],
            [ 'municipio_id' => 100, 'nombre_localidad' => 'Santos de Abelgas'],
            [ 'municipio_id' => 101, 'nombre_localidad' => 'Imataca'],
            [ 'municipio_id' => 101, 'nombre_localidad' => 'Cinco de Julio'],
            [ 'municipio_id' => 101, 'nombre_localidad' => 'Juan Bautista Arismendi'],
            [ 'municipio_id' => 101, 'nombre_localidad' => 'Manuel Piar'],
            [ 'municipio_id' => 101, 'nombre_localidad' => 'Rómulo Gallegos'],
            [ 'municipio_id' => 102, 'nombre_localidad' => 'Pedernales'],
            [ 'municipio_id' => 102, 'nombre_localidad' => 'Luis Beltrán Prieto Figueroa'],
            [ 'municipio_id' => 103, 'nombre_localidad' => 'San José (Delta Amacuro)'],
            [ 'municipio_id' => 103, 'nombre_localidad' => 'José Vidal Marcano'],
            [ 'municipio_id' => 103, 'nombre_localidad' => 'Juan Millán'],
            [ 'municipio_id' => 103, 'nombre_localidad' => 'Leonardo Ruíz Pineda'],
            [ 'municipio_id' => 103, 'nombre_localidad' => 'Mariscal Antonio José de Sucre'],
            [ 'municipio_id' => 103, 'nombre_localidad' => 'Monseñor Argimiro García'],
            [ 'municipio_id' => 103, 'nombre_localidad' => 'San Rafael (Delta Amacuro)'],
            [ 'municipio_id' => 103, 'nombre_localidad' => 'Virgen del Valle'],
            [ 'municipio_id' => 10, 'nombre_localidad' => 'Clarines'],
            [ 'municipio_id' => 10, 'nombre_localidad' => 'Guanape'],
            [ 'municipio_id' => 10, 'nombre_localidad' => 'Sabana de Uchire'],
            [ 'municipio_id' => 104, 'nombre_localidad' => 'Capadare'],
            [ 'municipio_id' => 104, 'nombre_localidad' => 'La Pastora'],
            [ 'municipio_id' => 104, 'nombre_localidad' => 'Libertador'],
            [ 'municipio_id' => 104, 'nombre_localidad' => 'San Juan de los Cayos'],
            [ 'municipio_id' => 105, 'nombre_localidad' => 'Aracua'],
            [ 'municipio_id' => 105, 'nombre_localidad' => 'La Peña'],
            [ 'municipio_id' => 105, 'nombre_localidad' => 'San Luis'],
            [ 'municipio_id' => 106, 'nombre_localidad' => 'Bariro'],
            [ 'municipio_id' => 106, 'nombre_localidad' => 'Borojó'],
            [ 'municipio_id' => 106, 'nombre_localidad' => 'Capatárida'],
            [ 'municipio_id' => 106, 'nombre_localidad' => 'Guajiro'],
            [ 'municipio_id' => 106, 'nombre_localidad' => 'Seque'],
            [ 'municipio_id' => 106, 'nombre_localidad' => 'Zazárida'],
            [ 'municipio_id' => 106, 'nombre_localidad' => 'Valle de Eroa'],
            [ 'municipio_id' => 107, 'nombre_localidad' => 'Cacique Manaure'],
            [ 'municipio_id' => 108, 'nombre_localidad' => 'Norte'],
            [ 'municipio_id' => 108, 'nombre_localidad' => 'Carirubana'],
            [ 'municipio_id' => 108, 'nombre_localidad' => 'Santa Ana'],
            [ 'municipio_id' => 108, 'nombre_localidad' => 'Urbana Punta Cardón'],
            [ 'municipio_id' => 109, 'nombre_localidad' => 'La Vela de Coro'],
            [ 'municipio_id' => 109, 'nombre_localidad' => 'Acurigua'],
            [ 'municipio_id' => 109, 'nombre_localidad' => 'Guaibacoa'],
            [ 'municipio_id' => 109, 'nombre_localidad' => 'Las Calderas'],
            [ 'municipio_id' => 109, 'nombre_localidad' => 'Macoruca'],
            [ 'municipio_id' => 110, 'nombre_localidad' => 'Dabajuro'],
            [ 'municipio_id' => 111, 'nombre_localidad' => 'Agua Clara'],
            [ 'municipio_id' => 111, 'nombre_localidad' => 'Avaria'],
            [ 'municipio_id' => 111, 'nombre_localidad' => 'Pedregal'],
            [ 'municipio_id' => 111, 'nombre_localidad' => 'Piedra Grande'],
            [ 'municipio_id' => 111, 'nombre_localidad' => 'Purureche'],
            [ 'municipio_id' => 112, 'nombre_localidad' => 'Adaure'],
            [ 'municipio_id' => 112, 'nombre_localidad' => 'Adícora'],
            [ 'municipio_id' => 112, 'nombre_localidad' => 'Baraived'],
            [ 'municipio_id' => 112, 'nombre_localidad' => 'Buena Vista'],
            [ 'municipio_id' => 112, 'nombre_localidad' => 'Jadacaquiva'],
            [ 'municipio_id' => 112, 'nombre_localidad' => 'El Vínculo'],
            [ 'municipio_id' => 112, 'nombre_localidad' => 'El Hato'],
            [ 'municipio_id' => 112, 'nombre_localidad' => 'Moruy'],
            [ 'municipio_id' => 112, 'nombre_localidad' => 'Pueblo Nuevo'],
            [ 'municipio_id' => 113, 'nombre_localidad' => 'Agua Larga'],
            [ 'municipio_id' => 113, 'nombre_localidad' => 'Churuguara'],
            [ 'municipio_id' => 113, 'nombre_localidad' => 'El Paují'],
            [ 'municipio_id' => 113, 'nombre_localidad' => 'Independencia'],
            [ 'municipio_id' => 113, 'nombre_localidad' => 'Mapararí'],
            [ 'municipio_id' => 114, 'nombre_localidad' => 'Agua Linda'],
            [ 'municipio_id' => 114, 'nombre_localidad' => 'Araurima'],
            [ 'municipio_id' => 114, 'nombre_localidad' => 'Jacura'],
            [ 'municipio_id' => 115, 'nombre_localidad' => 'Tucacas'],
            [ 'municipio_id' => 115, 'nombre_localidad' => 'Boca de Aroa'],
            [ 'municipio_id' => 116, 'nombre_localidad' => 'Los Taques'],
            [ 'municipio_id' => 116, 'nombre_localidad' => 'Judibana'],
            [ 'municipio_id' => 117, 'nombre_localidad' => 'Mene de Mauroa'],
            [ 'municipio_id' => 117, 'nombre_localidad' => 'San Félix'],
            [ 'municipio_id' => 117, 'nombre_localidad' => 'Casigua'],
            [ 'municipio_id' => 118, 'nombre_localidad' => 'Guzmán Guillermo'],
            [ 'municipio_id' => 118, 'nombre_localidad' => 'Mitare'],
            [ 'municipio_id' => 118, 'nombre_localidad' => 'Río Seco'],
            [ 'municipio_id' => 118, 'nombre_localidad' => 'Sabaneta'],
            [ 'municipio_id' => 118, 'nombre_localidad' => 'San Antonio'],
            [ 'municipio_id' => 118, 'nombre_localidad' => 'San Gabriel'],
            [ 'municipio_id' => 118, 'nombre_localidad' => 'Santa Ana'],
            [ 'municipio_id' => 119, 'nombre_localidad' => 'Boca del Tocuyo'],
            [ 'municipio_id' => 119, 'nombre_localidad' => 'Chichiriviche'],
            [ 'municipio_id' => 119, 'nombre_localidad' => 'Tocuyo de la Costa'],
            [ 'municipio_id' => 120, 'nombre_localidad' => 'Palmasola'],
            [ 'municipio_id' => 121, 'nombre_localidad' => 'Cabure'],
            [ 'municipio_id' => 121, 'nombre_localidad' => 'Colina'],
            [ 'municipio_id' => 121, 'nombre_localidad' => 'Curimagua'],
            [ 'municipio_id' => 122, 'nombre_localidad' => 'San José de la Costa'],
            [ 'municipio_id' => 122, 'nombre_localidad' => 'Píritu'],
            [ 'municipio_id' => 123, 'nombre_localidad' => 'San Francisco'],
            [ 'municipio_id' => 124, 'nombre_localidad' => 'Sucre'],
            [ 'municipio_id' => 124, 'nombre_localidad' => 'Pecaya'],
            [ 'municipio_id' => 125, 'nombre_localidad' => 'Tocópero'],
            [ 'municipio_id' => 126, 'nombre_localidad' => 'El Charal'],
            [ 'municipio_id' => 126, 'nombre_localidad' => 'Las Vegas del Tuy'],
            [ 'municipio_id' => 126, 'nombre_localidad' => 'Santa Cruz de Bucaral'],
            [ 'municipio_id' => 127, 'nombre_localidad' => 'Bruzual'],
            [ 'municipio_id' => 127, 'nombre_localidad' => 'Urumaco'],
            [ 'municipio_id' => 128, 'nombre_localidad' => 'Puerto Cumarebo'],
            [ 'municipio_id' => 128, 'nombre_localidad' => 'La Ciénaga'],
            [ 'municipio_id' => 128, 'nombre_localidad' => 'La Soledad'],
            [ 'municipio_id' => 128, 'nombre_localidad' => 'Pueblo Cumarebo'],
            [ 'municipio_id' => 128, 'nombre_localidad' => 'Zazárida'],
            [ 'municipio_id' => 113, 'nombre_localidad' => 'Churuguara'],
            [ 'municipio_id' => 129, 'nombre_localidad' => 'Camaguán'],
            [ 'municipio_id' => 129, 'nombre_localidad' => 'Puerto Miranda'],
            [ 'municipio_id' => 129, 'nombre_localidad' => 'Uverito'],
            [ 'municipio_id' => 130, 'nombre_localidad' => 'Chaguaramas'],
            [ 'municipio_id' => 131, 'nombre_localidad' => 'El Socorro'],
            [ 'municipio_id' => 132, 'nombre_localidad' => 'Tucupido'],
            [ 'municipio_id' => 132, 'nombre_localidad' => 'San Rafael de Laya'],
            [ 'municipio_id' => 133, 'nombre_localidad' => 'Altagracia de Orituco'],
            [ 'municipio_id' => 133, 'nombre_localidad' => 'San Rafael de Orituco'],
            [ 'municipio_id' => 133, 'nombre_localidad' => 'San Francisco Javier de Lezama'],
            [ 'municipio_id' => 133, 'nombre_localidad' => 'Paso Real de Macaira'],
            [ 'municipio_id' => 133, 'nombre_localidad' => 'Carlos Soublette'],
            [ 'municipio_id' => 133, 'nombre_localidad' => 'San Francisco de Macaira'],
            [ 'municipio_id' => 133, 'nombre_localidad' => 'Libertad de Orituco'],
            [ 'municipio_id' => 134, 'nombre_localidad' => 'Cantaclaro'],
            [ 'municipio_id' => 134, 'nombre_localidad' => 'San Juan de los Morros'],
            [ 'municipio_id' => 134, 'nombre_localidad' => 'Parapara'],
            [ 'municipio_id' => 135, 'nombre_localidad' => 'El Sombrero'],
            [ 'municipio_id' => 135, 'nombre_localidad' => 'Sosa'],
            [ 'municipio_id' => 136, 'nombre_localidad' => 'Las Mercedes'],
            [ 'municipio_id' => 136, 'nombre_localidad' => 'Cabruta'],
            [ 'municipio_id' => 136, 'nombre_localidad' => 'Santa Rita de Manapire'],
            [ 'municipio_id' => 137, 'nombre_localidad' => 'Valle de la Pascua'],
            [ 'municipio_id' => 137, 'nombre_localidad' => 'Espino'],
            [ 'municipio_id' => 138, 'nombre_localidad' => 'San José de Unare'],
            [ 'municipio_id' => 138, 'nombre_localidad' => 'Zaraza'],
            [ 'municipio_id' => 139, 'nombre_localidad' => 'San José de Tiznados'],
            [ 'municipio_id' => 139, 'nombre_localidad' => 'San Francisco de Tiznados'],
            [ 'municipio_id' => 139, 'nombre_localidad' => 'San Lorenzo de Tiznados'],
            [ 'municipio_id' => 139, 'nombre_localidad' => 'Ortiz'],
            [ 'municipio_id' => 140, 'nombre_localidad' => 'Guayabal'],
            [ 'municipio_id' => 140, 'nombre_localidad' => 'Cazorla'],
            [ 'municipio_id' => 141, 'nombre_localidad' => 'San José de Guaribe'],
            [ 'municipio_id' => 141, 'nombre_localidad' => 'Uveral'],
            [ 'municipio_id' => 142, 'nombre_localidad' => 'Santa María de Ipire'],
            [ 'municipio_id' => 142, 'nombre_localidad' => 'Altamira'],
            [ 'municipio_id' => 143, 'nombre_localidad' => 'El Calvario'],
            [ 'municipio_id' => 143, 'nombre_localidad' => 'El Rastro'],
            [ 'municipio_id' => 143, 'nombre_localidad' => 'Guardatinajas'],
            [ 'municipio_id' => 143, 'nombre_localidad' => 'Capital Urbana Calabozo'],
            [ 'municipio_id' => 144, 'nombre_localidad' => 'Quebrada Honda de Guache'],
            [ 'municipio_id' => 144, 'nombre_localidad' => 'Pío Tamayo'],
            [ 'municipio_id' => 144, 'nombre_localidad' => 'Yacambú'],
            [ 'municipio_id' => 145, 'nombre_localidad' => 'Fréitez'],
            [ 'municipio_id' => 145, 'nombre_localidad' => 'José María Blanco'],
            [ 'municipio_id' => 146, 'nombre_localidad' => 'Catedral'],
            [ 'municipio_id' => 146, 'nombre_localidad' => 'Concepción'],
            [ 'municipio_id' => 146, 'nombre_localidad' => 'El Cují'],
            [ 'municipio_id' => 146, 'nombre_localidad' => 'Juan de Villegas'],
            [ 'municipio_id' => 146, 'nombre_localidad' => 'Santa Rosa'],
            [ 'municipio_id' => 146, 'nombre_localidad' => 'Tamaca'],
            [ 'municipio_id' => 146, 'nombre_localidad' => 'Unión'],
            [ 'municipio_id' => 146, 'nombre_localidad' => 'Aguedo Felipe Alvarado'],
            [ 'municipio_id' => 146, 'nombre_localidad' => 'Buena Vista'],
            [ 'municipio_id' => 146, 'nombre_localidad' => 'Juárez'],
            [ 'municipio_id' => 147, 'nombre_localidad' => 'Juan Bautista Rodríguez'],
            [ 'municipio_id' => 147, 'nombre_localidad' => 'Cuara'],
            [ 'municipio_id' => 147, 'nombre_localidad' => 'Diego de Lozada'],
            [ 'municipio_id' => 147, 'nombre_localidad' => 'Paraíso de San José'],
            [ 'municipio_id' => 147, 'nombre_localidad' => 'San Miguel'],
            [ 'municipio_id' => 147, 'nombre_localidad' => 'Tintorero'],
            [ 'municipio_id' => 147, 'nombre_localidad' => 'José Bernardo Dorante'],
            [ 'municipio_id' => 147, 'nombre_localidad' => 'Coronel Mariano Peraza '],
            [ 'municipio_id' => 148, 'nombre_localidad' => 'Bolívar'],
            [ 'municipio_id' => 148, 'nombre_localidad' => 'Anzoátegui'],
            [ 'municipio_id' => 148, 'nombre_localidad' => 'Guarico'],
            [ 'municipio_id' => 148, 'nombre_localidad' => 'Hilario Luna y Luna'],
            [ 'municipio_id' => 148, 'nombre_localidad' => 'Humocaro Alto'],
            [ 'municipio_id' => 148, 'nombre_localidad' => 'Humocaro Bajo'],
            [ 'municipio_id' => 148, 'nombre_localidad' => 'La Candelaria'],
            [ 'municipio_id' => 148, 'nombre_localidad' => 'Morán'],
            [ 'municipio_id' => 149, 'nombre_localidad' => 'Cabudare'],
            [ 'municipio_id' => 149, 'nombre_localidad' => 'José Gregorio Bastidas'],
            [ 'municipio_id' => 149, 'nombre_localidad' => 'Agua Viva'],
            [ 'municipio_id' => 150, 'nombre_localidad' => 'Sarare'],
            [ 'municipio_id' => 150, 'nombre_localidad' => 'Buría'],
            [ 'municipio_id' => 150, 'nombre_localidad' => 'Gustavo Vegas León'],
            [ 'municipio_id' => 151, 'nombre_localidad' => 'Trinidad Samuel'],
            [ 'municipio_id' => 151, 'nombre_localidad' => 'Antonio Díaz'],
            [ 'municipio_id' => 151, 'nombre_localidad' => 'Camacaro'],
            [ 'municipio_id' => 151, 'nombre_localidad' => 'Castañeda'],
            [ 'municipio_id' => 151, 'nombre_localidad' => 'Cecilio Zubillaga'],
            [ 'municipio_id' => 151, 'nombre_localidad' => 'Chiquinquirá'],
            [ 'municipio_id' => 151, 'nombre_localidad' => 'El Blanco'],
            [ 'municipio_id' => 151, 'nombre_localidad' => 'Espinoza de los Monteros'],
            [ 'municipio_id' => 151, 'nombre_localidad' => 'Lara'],
            [ 'municipio_id' => 151, 'nombre_localidad' => 'Las Mercedes'],
            [ 'municipio_id' => 151, 'nombre_localidad' => 'Manuel Morillo'],
            [ 'municipio_id' => 151, 'nombre_localidad' => 'Montaña Verde'],
            [ 'municipio_id' => 151, 'nombre_localidad' => 'Montes de Oca'],
            [ 'municipio_id' => 151, 'nombre_localidad' => 'Torres'],
            [ 'municipio_id' => 151, 'nombre_localidad' => 'Heriberto Arroyo'],
            [ 'municipio_id' => 151, 'nombre_localidad' => 'Reyes Vargas'],
            [ 'municipio_id' => 151, 'nombre_localidad' => 'Altagracia'],
            [ 'municipio_id' => 152, 'nombre_localidad' => 'Siquisique'],
            [ 'municipio_id' => 152, 'nombre_localidad' => 'Moroturo'],
            [ 'municipio_id' => 152, 'nombre_localidad' => 'San Miguel'],
            [ 'municipio_id' => 152, 'nombre_localidad' => 'Xaguas'],
            [ 'municipio_id' => 179, 'nombre_localidad' => 'Presidente Betancourt'],
            [ 'municipio_id' => 179, 'nombre_localidad' => 'Presidente Páez'],
            [ 'municipio_id' => 179, 'nombre_localidad' => 'Presidente Rómulo Gallegos'],
            [ 'municipio_id' => 179, 'nombre_localidad' => 'Gabriel Picón González'],
            [ 'municipio_id' => 179, 'nombre_localidad' => 'Héctor Amable Mora'],
            [ 'municipio_id' => 179, 'nombre_localidad' => 'José Nucete Sardi'],
            [ 'municipio_id' => 179, 'nombre_localidad' => 'Pulido Méndez'],
            [ 'municipio_id' => 180, 'nombre_localidad' => 'La Azulita'],
            [ 'municipio_id' => 181, 'nombre_localidad' => 'Santa Cruz de Mora'],
            [ 'municipio_id' => 181, 'nombre_localidad' => 'Mesa Bolívar'],
            [ 'municipio_id' => 181, 'nombre_localidad' => 'Mesa de Las Palmas'],
            [ 'municipio_id' => 182, 'nombre_localidad' => 'Aricagua'],
            [ 'municipio_id' => 182, 'nombre_localidad' => 'San Antonio'],
            [ 'municipio_id' => 183, 'nombre_localidad' => 'Canagua'],
            [ 'municipio_id' => 183, 'nombre_localidad' => 'Capurí'],
            [ 'municipio_id' => 183, 'nombre_localidad' => 'Chacantá'],
            [ 'municipio_id' => 183, 'nombre_localidad' => 'El Molino'],
            [ 'municipio_id' => 183, 'nombre_localidad' => 'Guaimaral'],
            [ 'municipio_id' => 183, 'nombre_localidad' => 'Mucutuy'],
            [ 'municipio_id' => 183, 'nombre_localidad' => 'Mucuchachí'],
            [ 'municipio_id' => 184, 'nombre_localidad' => 'Fernández Peña'],
            [ 'municipio_id' => 184, 'nombre_localidad' => 'Matriz'],
            [ 'municipio_id' => 184, 'nombre_localidad' => 'Montalbán'],
            [ 'municipio_id' => 184, 'nombre_localidad' => 'Acequias'],
            [ 'municipio_id' => 184, 'nombre_localidad' => 'Jají'],
            [ 'municipio_id' => 184, 'nombre_localidad' => 'La Mesa'],
            [ 'municipio_id' => 184, 'nombre_localidad' => 'San José del Sur'],
            [ 'municipio_id' => 185, 'nombre_localidad' => 'Tucaní'],
            [ 'municipio_id' => 185, 'nombre_localidad' => 'Florencio Ramírez'],
            [ 'municipio_id' => 186, 'nombre_localidad' => 'Santo Domingo'],
            [ 'municipio_id' => 186, 'nombre_localidad' => 'Las Piedras'],
            [ 'municipio_id' => 187, 'nombre_localidad' => 'Guaraque'],
            [ 'municipio_id' => 187, 'nombre_localidad' => 'Mesa de Quintero'],
            [ 'municipio_id' => 187, 'nombre_localidad' => 'Río Negro'],
            [ 'municipio_id' => 188, 'nombre_localidad' => 'Arapuey'],
            [ 'municipio_id' => 188, 'nombre_localidad' => 'Palmira'],
            [ 'municipio_id' => 189, 'nombre_localidad' => 'San Cristóbal de Torondoy'],
            [ 'municipio_id' => 189, 'nombre_localidad' => 'Torondoy'],
            [ 'municipio_id' => 190, 'nombre_localidad' => 'Antonio Spinetti Dini'],
            [ 'municipio_id' => 190, 'nombre_localidad' => 'Arias'],
            [ 'municipio_id' => 190, 'nombre_localidad' => 'Caracciolo Parra Pérez'],
            [ 'municipio_id' => 190, 'nombre_localidad' => 'Domingo Peña'],
            [ 'municipio_id' => 190, 'nombre_localidad' => 'El Llano'],
            [ 'municipio_id' => 190, 'nombre_localidad' => 'Gonzalo Picón Febres'],
            [ 'municipio_id' => 190, 'nombre_localidad' => 'Jacinto Plaza'],
            [ 'municipio_id' => 190, 'nombre_localidad' => 'Juan Rodríguez Suárez'],
            [ 'municipio_id' => 190, 'nombre_localidad' => 'Lasso de la Vega'],
            [ 'municipio_id' => 190, 'nombre_localidad' => 'Mariano Picón Salas'],
            [ 'municipio_id' => 190, 'nombre_localidad' => 'Milla'],
            [ 'municipio_id' => 190, 'nombre_localidad' => 'Osuna Rodríguez'],
            [ 'municipio_id' => 190, 'nombre_localidad' => 'Sagrario'],
            [ 'municipio_id' => 190, 'nombre_localidad' => 'El Morro'],
            [ 'municipio_id' => 190, 'nombre_localidad' => 'Los Nevados'],
            [ 'municipio_id' => 191, 'nombre_localidad' => 'Andrés Eloy Blanco'],
            [ 'municipio_id' => 191, 'nombre_localidad' => 'La Venta'],
            [ 'municipio_id' => 191, 'nombre_localidad' => 'Piñango'],
            [ 'municipio_id' => 191, 'nombre_localidad' => 'Timotes'],
            [ 'municipio_id' => 192, 'nombre_localidad' => 'Eloy Paredes'],
            [ 'municipio_id' => 192, 'nombre_localidad' => 'San Rafael de Alcázar'],
            [ 'municipio_id' => 192, 'nombre_localidad' => 'Santa Elena de Arenales'],
            [ 'municipio_id' => 193, 'nombre_localidad' => 'Santa María de Caparo'],
            [ 'municipio_id' => 194, 'nombre_localidad' => 'Pueblo Llano'],
            [ 'municipio_id' => 195, 'nombre_localidad' => 'Cacute'],
            [ 'municipio_id' => 195, 'nombre_localidad' => 'La Toma'],
            [ 'municipio_id' => 195, 'nombre_localidad' => 'Mucuchíes'],
            [ 'municipio_id' => 195, 'nombre_localidad' => 'Mucurubá'],
            [ 'municipio_id' => 195, 'nombre_localidad' => 'San Rafael'],
            [ 'municipio_id' => 196, 'nombre_localidad' => 'Gerónimo Maldonado'],
            [ 'municipio_id' => 196, 'nombre_localidad' => 'Bailadores'],
            [ 'municipio_id' => 197, 'nombre_localidad' => 'Tabay'],
            [ 'municipio_id' => 198, 'nombre_localidad' => 'Chiguará'],
            [ 'municipio_id' => 198, 'nombre_localidad' => 'Estánquez'],
            [ 'municipio_id' => 198, 'nombre_localidad' => 'Lagunillas'],
            [ 'municipio_id' => 198, 'nombre_localidad' => 'La Trampa'],
            [ 'municipio_id' => 198, 'nombre_localidad' => 'Pueblo Nuevo del Sur'],
            [ 'municipio_id' => 198, 'nombre_localidad' => 'San Juan'],
            [ 'municipio_id' => 199, 'nombre_localidad' => 'El Amparo'],
            [ 'municipio_id' => 199, 'nombre_localidad' => 'El Llano'],
            [ 'municipio_id' => 199, 'nombre_localidad' => 'San Francisco'],
            [ 'municipio_id' => 199, 'nombre_localidad' => 'Tovar'],
            [ 'municipio_id' => 200, 'nombre_localidad' => 'Independencia'],
            [ 'municipio_id' => 200, 'nombre_localidad' => 'María de la Concepción Palacios Blanco'],
            [ 'municipio_id' => 200, 'nombre_localidad' => 'Nueva Bolivia'],
            [ 'municipio_id' => 200, 'nombre_localidad' => 'Santa Apolonia'],
            [ 'municipio_id' => 201, 'nombre_localidad' => 'Caño El Tigre'],
            [ 'municipio_id' => 201, 'nombre_localidad' => 'Zea'],
            [ 'municipio_id' => 223, 'nombre_localidad' => 'Aragüita'],
            [ 'municipio_id' => 223, 'nombre_localidad' => 'Arévalo González'],
            [ 'municipio_id' => 223, 'nombre_localidad' => 'Capaya'],
            [ 'municipio_id' => 223, 'nombre_localidad' => 'Caucagua'],
            [ 'municipio_id' => 223, 'nombre_localidad' => 'Panaquire'],
            [ 'municipio_id' => 223, 'nombre_localidad' => 'Ribas'],
            [ 'municipio_id' => 223, 'nombre_localidad' => 'El Café'],
            [ 'municipio_id' => 223, 'nombre_localidad' => 'Marizapa'],
            [ 'municipio_id' => 224, 'nombre_localidad' => 'Cumbo'],
            [ 'municipio_id' => 224, 'nombre_localidad' => 'San José de Barlovento'],
            [ 'municipio_id' => 225, 'nombre_localidad' => 'El Cafetal'],
            [ 'municipio_id' => 225, 'nombre_localidad' => 'Las Minas'],
            [ 'municipio_id' => 225, 'nombre_localidad' => 'Nuestra Señora del Rosario'],
            [ 'municipio_id' => 226, 'nombre_localidad' => 'Higuerote'],
            [ 'municipio_id' => 226, 'nombre_localidad' => 'Curiepe'],
            [ 'municipio_id' => 226, 'nombre_localidad' => 'Tacarigua de Brión'],
            [ 'municipio_id' => 227, 'nombre_localidad' => 'Mamporal'],
            [ 'municipio_id' => 228, 'nombre_localidad' => 'Carrizal'],
            [ 'municipio_id' => 229, 'nombre_localidad' => 'Chacao'],
            [ 'municipio_id' => 230, 'nombre_localidad' => 'Charallave'],
            [ 'municipio_id' => 230, 'nombre_localidad' => 'Las Brisas'],
            [ 'municipio_id' => 231, 'nombre_localidad' => 'El Hatillo'],
            [ 'municipio_id' => 232, 'nombre_localidad' => 'Altagracia de la Montaña'],
            [ 'municipio_id' => 232, 'nombre_localidad' => 'Cecilio Acosta'],
            [ 'municipio_id' => 232, 'nombre_localidad' => 'Los Teques'],
            [ 'municipio_id' => 232, 'nombre_localidad' => 'El Jarillo'],
            [ 'municipio_id' => 232, 'nombre_localidad' => 'San Pedro'],
            [ 'municipio_id' => 232, 'nombre_localidad' => 'Tácata'],
            [ 'municipio_id' => 232, 'nombre_localidad' => 'Paracotos'],
            [ 'municipio_id' => 233, 'nombre_localidad' => 'Cartanal'],
            [ 'municipio_id' => 233, 'nombre_localidad' => 'Santa Teresa del Tuy'],
            [ 'municipio_id' => 234, 'nombre_localidad' => 'La Democracia'],
            [ 'municipio_id' => 234, 'nombre_localidad' => 'Ocumare del Tuy'],
            [ 'municipio_id' => 234, 'nombre_localidad' => 'Santa Bárbara'],
            [ 'municipio_id' => 235, 'nombre_localidad' => 'San Antonio de los Altos'],
            [ 'municipio_id' => 236, 'nombre_localidad' => 'Río Chico'],
            [ 'municipio_id' => 236, 'nombre_localidad' => 'El Guapo'],
            [ 'municipio_id' => 236, 'nombre_localidad' => 'Tacarigua de la Laguna'],
            [ 'municipio_id' => 236, 'nombre_localidad' => 'Paparo'],
            [ 'municipio_id' => 236, 'nombre_localidad' => 'San Fernando del Guapo'],
            [ 'municipio_id' => 237, 'nombre_localidad' => 'Santa Lucía del Tuy'],
            [ 'municipio_id' => 238, 'nombre_localidad' => 'Cúpira'],
            [ 'municipio_id' => 238, 'nombre_localidad' => 'Machurucuto'],
            [ 'municipio_id' => 239, 'nombre_localidad' => 'Guarenas'],
            [ 'municipio_id' => 240, 'nombre_localidad' => 'San Antonio de Yare'],
            [ 'municipio_id' => 240, 'nombre_localidad' => 'San Francisco de Yare'],
            [ 'municipio_id' => 241, 'nombre_localidad' => 'Leoncio Martínez'],
            [ 'municipio_id' => 241, 'nombre_localidad' => 'Petare'],
            [ 'municipio_id' => 241, 'nombre_localidad' => 'Caucagüita'],
            [ 'municipio_id' => 241, 'nombre_localidad' => 'Filas de Mariche'],
            [ 'municipio_id' => 241, 'nombre_localidad' => 'La Dolorita'],
            [ 'municipio_id' => 242, 'nombre_localidad' => 'Cúa'],
            [ 'municipio_id' => 242, 'nombre_localidad' => 'Nueva Cúa'],
            [ 'municipio_id' => 243, 'nombre_localidad' => 'Guatire'],
            [ 'municipio_id' => 243, 'nombre_localidad' => 'Bolívar'],
            [ 'municipio_id' => 258, 'nombre_localidad' => 'San Antonio de Maturín'],
            [ 'municipio_id' => 258, 'nombre_localidad' => 'San Francisco de Maturín'],
            [ 'municipio_id' => 259, 'nombre_localidad' => 'Aguasay'],
            [ 'municipio_id' => 260, 'nombre_localidad' => 'Caripito'],
            [ 'municipio_id' => 261, 'nombre_localidad' => 'El Guácharo'],
            [ 'municipio_id' => 261, 'nombre_localidad' => 'La Guanota'],
            [ 'municipio_id' => 261, 'nombre_localidad' => 'Sabana de Piedra'],
            [ 'municipio_id' => 261, 'nombre_localidad' => 'San Agustín'],
            [ 'municipio_id' => 261, 'nombre_localidad' => 'Teresen'],
            [ 'municipio_id' => 261, 'nombre_localidad' => 'Caripe'],
            [ 'municipio_id' => 262, 'nombre_localidad' => 'Areo'],
            [ 'municipio_id' => 262, 'nombre_localidad' => 'Capital Cedeño'],
            [ 'municipio_id' => 262, 'nombre_localidad' => 'San Félix de Cantalicio'],
            [ 'municipio_id' => 262, 'nombre_localidad' => 'Viento Fresco'],
            [ 'municipio_id' => 263, 'nombre_localidad' => 'El Tejero'],
            [ 'municipio_id' => 263, 'nombre_localidad' => 'Punta de Mata'],
            [ 'municipio_id' => 264, 'nombre_localidad' => 'Chaguaramas'],
            [ 'municipio_id' => 264, 'nombre_localidad' => 'Las Alhuacas'],
            [ 'municipio_id' => 264, 'nombre_localidad' => 'Tabasca'],
            [ 'municipio_id' => 264, 'nombre_localidad' => 'Temblador'],
            [ 'municipio_id' => 265, 'nombre_localidad' => 'Alto de los Godos'],
            [ 'municipio_id' => 265, 'nombre_localidad' => 'Boquerón'],
            [ 'municipio_id' => 265, 'nombre_localidad' => 'Las Cocuizas'],
            [ 'municipio_id' => 265, 'nombre_localidad' => 'La Cruz'],
            [ 'municipio_id' => 265, 'nombre_localidad' => 'San Simón'],
            [ 'municipio_id' => 265, 'nombre_localidad' => 'El Corozo'],
            [ 'municipio_id' => 265, 'nombre_localidad' => 'El Furrial'],
            [ 'municipio_id' => 265, 'nombre_localidad' => 'Jusepín'],
            [ 'municipio_id' => 265, 'nombre_localidad' => 'La Pica'],
            [ 'municipio_id' => 265, 'nombre_localidad' => 'San Vicente'],
            [ 'municipio_id' => 266, 'nombre_localidad' => 'Aparicio'],
            [ 'municipio_id' => 266, 'nombre_localidad' => 'Aragua de Maturín'],
            [ 'municipio_id' => 266, 'nombre_localidad' => 'Chaguaramal'],
            [ 'municipio_id' => 266, 'nombre_localidad' => 'El Pinto'],
            [ 'municipio_id' => 266, 'nombre_localidad' => 'Guanaguana'],
            [ 'municipio_id' => 266, 'nombre_localidad' => 'La Toscana'],
            [ 'municipio_id' => 266, 'nombre_localidad' => 'Taguaya'],
            [ 'municipio_id' => 267, 'nombre_localidad' => 'Cachipo'],
            [ 'municipio_id' => 267, 'nombre_localidad' => 'Quiriquire'],
            [ 'municipio_id' => 268, 'nombre_localidad' => 'Santa Bárbara'],
            [ 'municipio_id' => 269, 'nombre_localidad' => 'Barrancas'],
            [ 'municipio_id' => 269, 'nombre_localidad' => 'Los Barrancos de Fajardo'],
            [ 'municipio_id' => 270, 'nombre_localidad' => 'Uracoa'],
            [ 'municipio_id' => 271, 'nombre_localidad' => 'Antolín del Campo'],
            [ 'municipio_id' => 272, 'nombre_localidad' => 'Arismendi'],
            [ 'municipio_id' => 273, 'nombre_localidad' => 'García'],
            [ 'municipio_id' => 273, 'nombre_localidad' => 'Francisco Fajardo'],
            [ 'municipio_id' => 274, 'nombre_localidad' => 'Bolívar'],
            [ 'municipio_id' => 274, 'nombre_localidad' => 'Guevara'],
            [ 'municipio_id' => 274, 'nombre_localidad' => 'Matasiete'],
            [ 'municipio_id' => 274, 'nombre_localidad' => 'Santa Ana'],
            [ 'municipio_id' => 274, 'nombre_localidad' => 'Sucre'],
            [ 'municipio_id' => 275, 'nombre_localidad' => 'Aguirre'],
            [ 'municipio_id' => 275, 'nombre_localidad' => 'Maneiro'],
            [ 'municipio_id' => 276, 'nombre_localidad' => 'Adrián'],
            [ 'municipio_id' => 276, 'nombre_localidad' => 'Juan Griego'],
            [ 'municipio_id' => 276, 'nombre_localidad' => 'Yaguaraparo'],
            [ 'municipio_id' => 277, 'nombre_localidad' => 'Porlamar'],
            [ 'municipio_id' => 278, 'nombre_localidad' => 'San Francisco de Macanao'],
            [ 'municipio_id' => 278, 'nombre_localidad' => 'Boca de Río'],
            [ 'municipio_id' => 279, 'nombre_localidad' => 'Tubores'],
            [ 'municipio_id' => 279, 'nombre_localidad' => 'Los Baleales'],
            [ 'municipio_id' => 280, 'nombre_localidad' => 'Vicente Fuentes'],
            [ 'municipio_id' => 280, 'nombre_localidad' => 'Villalba'],
            [ 'municipio_id' => 281, 'nombre_localidad' => 'San Juan Bautista'],
            [ 'municipio_id' => 281, 'nombre_localidad' => 'Zabala'],
            [ 'municipio_id' => 283, 'nombre_localidad' => 'Araure'],
            [ 'municipio_id' => 283, 'nombre_localidad' => 'Río Acarigua'],
            [ 'municipio_id' => 284, 'nombre_localidad' => 'Píritu'],
            [ 'municipio_id' => 284, 'nombre_localidad' => 'Uveral'],
            [ 'municipio_id' => 285, 'nombre_localidad' => 'Guanare'],
            [ 'municipio_id' => 285, 'nombre_localidad' => 'Córdoba'],
            [ 'municipio_id' => 285, 'nombre_localidad' => 'San José de la Montaña'],
            [ 'municipio_id' => 285, 'nombre_localidad' => 'San Juan de Guanaguanare'],
            [ 'municipio_id' => 285, 'nombre_localidad' => 'Virgen de la Coromoto'],
            [ 'municipio_id' => 286, 'nombre_localidad' => 'Guanarito'],
            [ 'municipio_id' => 286, 'nombre_localidad' => 'Trinidad de la Capilla'],
            [ 'municipio_id' => 286, 'nombre_localidad' => 'Divina Pastora'],
            [ 'municipio_id' => 287, 'nombre_localidad' => 'Monseñor José Vicente de Unda'],
            [ 'municipio_id' => 287, 'nombre_localidad' => 'Peña Blanca'],
            [ 'municipio_id' => 288, 'nombre_localidad' => 'Capital Ospino'],
            [ 'municipio_id' => 288, 'nombre_localidad' => 'Aparición'],
            [ 'municipio_id' => 288, 'nombre_localidad' => 'La Estación'],
            [ 'municipio_id' => 289, 'nombre_localidad' => 'Páez'],
            [ 'municipio_id' => 289, 'nombre_localidad' => 'Payara'],
            [ 'municipio_id' => 289, 'nombre_localidad' => 'Pimpinela'],
            [ 'municipio_id' => 289, 'nombre_localidad' => 'Ramón Peraza'],
            [ 'municipio_id' => 290, 'nombre_localidad' => 'Papelón'],
            [ 'municipio_id' => 290, 'nombre_localidad' => 'Caño Delgadito'],
            [ 'municipio_id' => 291, 'nombre_localidad' => 'San Genaro de Boconoíto'],
            [ 'municipio_id' => 291, 'nombre_localidad' => 'Antolín Tovar'],
            [ 'municipio_id' => 292, 'nombre_localidad' => 'San Rafael de Onoto'],
            [ 'municipio_id' => 292, 'nombre_localidad' => 'Santa Fe'],
            [ 'municipio_id' => 292, 'nombre_localidad' => 'Thermo Morles'],
            [ 'municipio_id' => 293, 'nombre_localidad' => 'Santa Rosalía'],
            [ 'municipio_id' => 293, 'nombre_localidad' => 'Florida'],
            [ 'municipio_id' => 294, 'nombre_localidad' => 'Sucre'],
            [ 'municipio_id' => 294, 'nombre_localidad' => 'Concepción'],
            [ 'municipio_id' => 294, 'nombre_localidad' => 'San Rafael de Palo Alzado'],
            [ 'municipio_id' => 294, 'nombre_localidad' => 'Uvencio Antonio Velásquez'],
            [ 'municipio_id' => 294, 'nombre_localidad' => 'San José de Saguaz'],
            [ 'municipio_id' => 294, 'nombre_localidad' => 'Villa Rosa'],
            [ 'municipio_id' => 295, 'nombre_localidad' => 'Turén'],
            [ 'municipio_id' => 295, 'nombre_localidad' => 'Canelones'],
            [ 'municipio_id' => 295, 'nombre_localidad' => 'Santa Cruz'],
            [ 'municipio_id' => 295, 'nombre_localidad' => 'San Isidro Labrador'],
            [ 'municipio_id' => 296, 'nombre_localidad' => 'Mariño'],
            [ 'municipio_id' => 296, 'nombre_localidad' => 'Rómulo Gallegos'],
            [ 'municipio_id' => 297, 'nombre_localidad' => 'San José de Aerocuar'],
            [ 'municipio_id' => 297, 'nombre_localidad' => 'Tavera Acosta'],
            [ 'municipio_id' => 298, 'nombre_localidad' => 'Río Caribe'],
            [ 'municipio_id' => 298, 'nombre_localidad' => 'Antonio José de Sucre'],
            [ 'municipio_id' => 298, 'nombre_localidad' => 'El Morro de Puerto Santo'],
            [ 'municipio_id' => 298, 'nombre_localidad' => 'Puerto Santo'],
            [ 'municipio_id' => 298, 'nombre_localidad' => 'San Juan de las Galdonas'],
            [ 'municipio_id' => 299, 'nombre_localidad' => 'El Pilar'],
            [ 'municipio_id' => 299, 'nombre_localidad' => 'El Rincón'],
            [ 'municipio_id' => 299, 'nombre_localidad' => 'General Francisco Antonio Váquez'],
            [ 'municipio_id' => 299, 'nombre_localidad' => 'Guaraúnos'],
            [ 'municipio_id' => 299, 'nombre_localidad' => 'Tunapuicito'],
            [ 'municipio_id' => 299, 'nombre_localidad' => 'Unión'],
            [ 'municipio_id' => 300, 'nombre_localidad' => 'Santa Catalina'],
            [ 'municipio_id' => 300, 'nombre_localidad' => 'Santa Rosa'],
            [ 'municipio_id' => 300, 'nombre_localidad' => 'Santa Teresa'],
            [ 'municipio_id' => 300, 'nombre_localidad' => 'Bolívar'],
            [ 'municipio_id' => 300, 'nombre_localidad' => 'Maracapana'],
            [ 'municipio_id' => 302, 'nombre_localidad' => 'Libertad'],
            [ 'municipio_id' => 302, 'nombre_localidad' => 'El Paujil'],
            [ 'municipio_id' => 302, 'nombre_localidad' => 'Yaguaraparo'],
            [ 'municipio_id' => 303, 'nombre_localidad' => 'Cruz Salmerón Acosta'],
            [ 'municipio_id' => 303, 'nombre_localidad' => 'Chacopata'],
            [ 'municipio_id' => 303, 'nombre_localidad' => 'Manicuare'],
            [ 'municipio_id' => 304, 'nombre_localidad' => 'Tunapuy'],
            [ 'municipio_id' => 304, 'nombre_localidad' => 'Campo Elías'],
            [ 'municipio_id' => 305, 'nombre_localidad' => 'Irapa'],
            [ 'municipio_id' => 305, 'nombre_localidad' => 'Campo Claro'],
            [ 'municipio_id' => 305, 'nombre_localidad' => 'Maraval'],
            [ 'municipio_id' => 305, 'nombre_localidad' => 'San Antonio de Irapa'],
            [ 'municipio_id' => 305, 'nombre_localidad' => 'Soro'],
            [ 'municipio_id' => 306, 'nombre_localidad' => 'Mejía'],
            [ 'municipio_id' => 307, 'nombre_localidad' => 'Cumanacoa'],
            [ 'municipio_id' => 307, 'nombre_localidad' => 'Arenas'],
            [ 'municipio_id' => 307, 'nombre_localidad' => 'Aricagua'],
            [ 'municipio_id' => 307, 'nombre_localidad' => 'Cogollar'],
            [ 'municipio_id' => 307, 'nombre_localidad' => 'San Fernando'],
            [ 'municipio_id' => 307, 'nombre_localidad' => 'San Lorenzo'],
            [ 'municipio_id' => 308, 'nombre_localidad' => 'Villa Frontado (Muelle de Cariaco)'],
            [ 'municipio_id' => 308, 'nombre_localidad' => 'Catuaro'],
            [ 'municipio_id' => 308, 'nombre_localidad' => 'Rendón'],
            [ 'municipio_id' => 308, 'nombre_localidad' => 'San Cruz'],
            [ 'municipio_id' => 308, 'nombre_localidad' => 'Santa María'],
            [ 'municipio_id' => 309, 'nombre_localidad' => 'Altagracia'],
            [ 'municipio_id' => 309, 'nombre_localidad' => 'Santa Inés'],
            [ 'municipio_id' => 309, 'nombre_localidad' => 'Valentín Valiente'],
            [ 'municipio_id' => 309, 'nombre_localidad' => 'Ayacucho'],
            [ 'municipio_id' => 309, 'nombre_localidad' => 'San Juan'],
            [ 'municipio_id' => 309, 'nombre_localidad' => 'Raúl Leoni'],
            [ 'municipio_id' => 309, 'nombre_localidad' => 'Gran Mariscal'],
            [ 'municipio_id' => 310, 'nombre_localidad' => 'Cristóbal Colón'],
            [ 'municipio_id' => 310, 'nombre_localidad' => 'Bideau'],
            [ 'municipio_id' => 310, 'nombre_localidad' => 'Punta de Piedras'],
            [ 'municipio_id' => 310, 'nombre_localidad' => 'Güiria'],
            [ 'municipio_id' => 341, 'nombre_localidad' => 'Andrés Bello'],
            [ 'municipio_id' => 342, 'nombre_localidad' => 'Antonio Rómulo Costa'],
            [ 'municipio_id' => 343, 'nombre_localidad' => 'Ayacucho'],
            [ 'municipio_id' => 343, 'nombre_localidad' => 'Rivas Berti'],
            [ 'municipio_id' => 343, 'nombre_localidad' => 'San Pedro del Río'],
            [ 'municipio_id' => 344, 'nombre_localidad' => 'Bolívar'],
            [ 'municipio_id' => 344, 'nombre_localidad' => 'Palotal'],
            [ 'municipio_id' => 344, 'nombre_localidad' => 'General Juan Vicente Gómez'],
            [ 'municipio_id' => 344, 'nombre_localidad' => 'Isaías Medina Angarita'],
            [ 'municipio_id' => 345, 'nombre_localidad' => 'Cárdenas'],
            [ 'municipio_id' => 345, 'nombre_localidad' => 'Amenodoro Ángel Lamus'],
            [ 'municipio_id' => 345, 'nombre_localidad' => 'La Florida'],
            [ 'municipio_id' => 346, 'nombre_localidad' => 'Córdoba'],
            [ 'municipio_id' => 347, 'nombre_localidad' => 'Fernández Feo'],
            [ 'municipio_id' => 347, 'nombre_localidad' => 'Alberto Adriani'],
            [ 'municipio_id' => 347, 'nombre_localidad' => 'Santo Domingo'],
            [ 'municipio_id' => 348, 'nombre_localidad' => 'Francisco de Miranda'],
            [ 'municipio_id' => 349, 'nombre_localidad' => 'García de Hevia'],
            [ 'municipio_id' => 349, 'nombre_localidad' => 'Boca de Grita'],
            [ 'municipio_id' => 349, 'nombre_localidad' => 'José Antonio Páez'],
            [ 'municipio_id' => 350, 'nombre_localidad' => 'Guásimos'],
            [ 'municipio_id' => 351, 'nombre_localidad' => 'Independencia'],
            [ 'municipio_id' => 351, 'nombre_localidad' => 'Juan Germán Roscio'],
            [ 'municipio_id' => 351, 'nombre_localidad' => 'Román Cárdenas'],
            [ 'municipio_id' => 352, 'nombre_localidad' => 'Jáuregui'],
            [ 'municipio_id' => 352, 'nombre_localidad' => 'Emilio Constantino Guerrero'],
            [ 'municipio_id' => 352, 'nombre_localidad' => 'Monseñor Miguel Antonio Salas'],
            [ 'municipio_id' => 353, 'nombre_localidad' => 'José María Vargas'],
            [ 'municipio_id' => 354, 'nombre_localidad' => 'Junín'],
            [ 'municipio_id' => 354, 'nombre_localidad' => 'La Petrólea'],
            [ 'municipio_id' => 354, 'nombre_localidad' => 'Quinimarí'],
            [ 'municipio_id' => 354, 'nombre_localidad' => 'Bramón'],
            [ 'municipio_id' => 355, 'nombre_localidad' => 'Libertad'],
            [ 'municipio_id' => 355, 'nombre_localidad' => 'Cipriano Castro'],
            [ 'municipio_id' => 355, 'nombre_localidad' => 'Manuel Felipe Rugeles'],
            [ 'municipio_id' => 356, 'nombre_localidad' => 'Libertador'],
            [ 'municipio_id' => 356, 'nombre_localidad' => 'Doradas'],
            [ 'municipio_id' => 356, 'nombre_localidad' => 'Emeterio Ochoa'],
            [ 'municipio_id' => 356, 'nombre_localidad' => 'San Joaquín de Navay'],
            [ 'municipio_id' => 357, 'nombre_localidad' => 'Lobatera'],
            [ 'municipio_id' => 357, 'nombre_localidad' => 'Constitución'],
            [ 'municipio_id' => 358, 'nombre_localidad' => 'Michelena'],
            [ 'municipio_id' => 359, 'nombre_localidad' => 'Panamericano'],
            [ 'municipio_id' => 359, 'nombre_localidad' => 'La Palmita'],
            [ 'municipio_id' => 360, 'nombre_localidad' => 'Pedro María Ureña'],
            [ 'municipio_id' => 360, 'nombre_localidad' => 'Nueva Arcadia'],
            [ 'municipio_id' => 361, 'nombre_localidad' => 'Delicias'],
            [ 'municipio_id' => 361, 'nombre_localidad' => 'Pecaya'],
            [ 'municipio_id' => 362, 'nombre_localidad' => 'Samuel Darío Maldonado'],
            [ 'municipio_id' => 362, 'nombre_localidad' => 'Boconó'],
            [ 'municipio_id' => 362, 'nombre_localidad' => 'Hernández'],
            [ 'municipio_id' => 363, 'nombre_localidad' => 'La Concordia'],
            [ 'municipio_id' => 363, 'nombre_localidad' => 'San Juan Bautista'],
            [ 'municipio_id' => 363, 'nombre_localidad' => 'Pedro María Morantes'],
            [ 'municipio_id' => 363, 'nombre_localidad' => 'San Sebastián'],
            [ 'municipio_id' => 363, 'nombre_localidad' => 'Dr. Francisco Romero Lobo'],
            [ 'municipio_id' => 364, 'nombre_localidad' => 'Seboruco'],
            [ 'municipio_id' => 365, 'nombre_localidad' => 'Simón Rodríguez'],
            [ 'municipio_id' => 366, 'nombre_localidad' => 'Sucre'],
            [ 'municipio_id' => 366, 'nombre_localidad' => 'Eleazar López Contreras'],
            [ 'municipio_id' => 366, 'nombre_localidad' => 'San Pablo'],
            [ 'municipio_id' => 367, 'nombre_localidad' => 'Torbes'],
            [ 'municipio_id' => 368, 'nombre_localidad' => 'Uribante'],
            [ 'municipio_id' => 368, 'nombre_localidad' => 'Cárdenas'],
            [ 'municipio_id' => 368, 'nombre_localidad' => 'Juan Pablo Peñalosa'],
            [ 'municipio_id' => 368, 'nombre_localidad' => 'Potosí'],
            [ 'municipio_id' => 369, 'nombre_localidad' => 'San Judas Tadeo'],
            [ 'municipio_id' => 370, 'nombre_localidad' => 'Araguaney'],
            [ 'municipio_id' => 370, 'nombre_localidad' => 'El Jaguito'],
            [ 'municipio_id' => 370, 'nombre_localidad' => 'La Esperanza'],
            [ 'municipio_id' => 370, 'nombre_localidad' => 'Santa Isabel'],
            [ 'municipio_id' => 371, 'nombre_localidad' => 'Boconó'],
            [ 'municipio_id' => 371, 'nombre_localidad' => 'El Carmen'],
            [ 'municipio_id' => 371, 'nombre_localidad' => 'Mosquey'],
            [ 'municipio_id' => 371, 'nombre_localidad' => 'Ayacucho'],
            [ 'municipio_id' => 371, 'nombre_localidad' => 'Burbusay'],
            [ 'municipio_id' => 371, 'nombre_localidad' => 'General Ribas'],
            [ 'municipio_id' => 371, 'nombre_localidad' => 'Guaramacal'],
            [ 'municipio_id' => 371, 'nombre_localidad' => 'Vega de Guaramacal'],
            [ 'municipio_id' => 371, 'nombre_localidad' => 'Monseñor Jáuregui'],
            [ 'municipio_id' => 371, 'nombre_localidad' => 'Rafael Rangel'],
            [ 'municipio_id' => 371, 'nombre_localidad' => 'San Miguel'],
            [ 'municipio_id' => 371, 'nombre_localidad' => 'San José'],
            [ 'municipio_id' => 372, 'nombre_localidad' => 'Sabana Grande'],
            [ 'municipio_id' => 372, 'nombre_localidad' => 'Cheregüé'],
            [ 'municipio_id' => 372, 'nombre_localidad' => 'Granados'],
            [ 'municipio_id' => 373, 'nombre_localidad' => 'Arnoldo Gabaldón'],
            [ 'municipio_id' => 373, 'nombre_localidad' => 'Bolivia'],
            [ 'municipio_id' => 373, 'nombre_localidad' => 'Carrillo'],
            [ 'municipio_id' => 373, 'nombre_localidad' => 'Cegarra'],
            [ 'municipio_id' => 373, 'nombre_localidad' => 'Chejendé'],
            [ 'municipio_id' => 373, 'nombre_localidad' => 'Manuel Salvador Ulloa'],
            [ 'municipio_id' => 373, 'nombre_localidad' => 'San José'],
            [ 'municipio_id' => 374, 'nombre_localidad' => 'Carache'],
            [ 'municipio_id' => 374, 'nombre_localidad' => 'La Concepción'],
            [ 'municipio_id' => 374, 'nombre_localidad' => 'Cuicas'],
            [ 'municipio_id' => 374, 'nombre_localidad' => 'Panamericana'],
            [ 'municipio_id' => 374, 'nombre_localidad' => 'Santa Cruz'],
            [ 'municipio_id' => 375, 'nombre_localidad' => 'Escuque'],
            [ 'municipio_id' => 375, 'nombre_localidad' => 'La Unión'],
            [ 'municipio_id' => 375, 'nombre_localidad' => 'Santa Rita'],
            [ 'municipio_id' => 375, 'nombre_localidad' => 'Sabana Libre'],
            [ 'municipio_id' => 376, 'nombre_localidad' => 'El Socorro'],
            [ 'municipio_id' => 376, 'nombre_localidad' => 'Los Caprichos'],
            [ 'municipio_id' => 376, 'nombre_localidad' => 'Antonio José de Sucre'],
            [ 'municipio_id' => 377, 'nombre_localidad' => 'Campo Elías'],
            [ 'municipio_id' => 377, 'nombre_localidad' => 'Arnoldo Gabaldón'],
            [ 'municipio_id' => 378, 'nombre_localidad' => 'Santa Apolonia'],
            [ 'municipio_id' => 378, 'nombre_localidad' => 'El Progreso'],
            [ 'municipio_id' => 378, 'nombre_localidad' => 'La Ceiba'],
            [ 'municipio_id' => 378, 'nombre_localidad' => 'Tres de Febrero'],
            [ 'municipio_id' => 379, 'nombre_localidad' => 'El Dividive'],
            [ 'municipio_id' => 379, 'nombre_localidad' => 'Agua Santa'],
            [ 'municipio_id' => 379, 'nombre_localidad' => 'Agua Caliente'],
            [ 'municipio_id' => 379, 'nombre_localidad' => 'El Cenizo'],
            [ 'municipio_id' => 379, 'nombre_localidad' => 'Valerita'],
            [ 'municipio_id' => 380, 'nombre_localidad' => 'Monte Carmelo'],
            [ 'municipio_id' => 380, 'nombre_localidad' => 'Buena Vista'],
            [ 'municipio_id' => 380, 'nombre_localidad' => 'Santa María del Horcón'],
            [ 'municipio_id' => 381, 'nombre_localidad' => 'Motatán'],
            [ 'municipio_id' => 381, 'nombre_localidad' => 'El Baño'],
            [ 'municipio_id' => 381, 'nombre_localidad' => 'Jalisco'],
            [ 'municipio_id' => 382, 'nombre_localidad' => 'Pampán'],
            [ 'municipio_id' => 382, 'nombre_localidad' => 'Flor de Patria'],
            [ 'municipio_id' => 382, 'nombre_localidad' => 'La Paz'],
            [ 'municipio_id' => 382, 'nombre_localidad' => 'Santa Ana'],
            [ 'municipio_id' => 383, 'nombre_localidad' => 'Pampanito'],
            [ 'municipio_id' => 383, 'nombre_localidad' => 'La Concepción'],
            [ 'municipio_id' => 383, 'nombre_localidad' => 'Pampanito II'],
            [ 'municipio_id' => 384, 'nombre_localidad' => 'Betijoque'],
            [ 'municipio_id' => 384, 'nombre_localidad' => 'José Gregorio Hernández'],
            [ 'municipio_id' => 384, 'nombre_localidad' => 'La Pueblita'],
            [ 'municipio_id' => 384, 'nombre_localidad' => 'Los Cedros'],
            [ 'municipio_id' => 385, 'nombre_localidad' => 'Carvajal'],
            [ 'municipio_id' => 385, 'nombre_localidad' => 'Campo Alegre'],
            [ 'municipio_id' => 385, 'nombre_localidad' => 'Antonio Nicolás Briceño'],
            [ 'municipio_id' => 385, 'nombre_localidad' => 'José Leonardo Suárez'],
            [ 'municipio_id' => 386, 'nombre_localidad' => 'Sabana de Mendoza'],
            [ 'municipio_id' => 386, 'nombre_localidad' => 'Junín'],
            [ 'municipio_id' => 386, 'nombre_localidad' => 'Valmore Rodríguez'],
            [ 'municipio_id' => 386, 'nombre_localidad' => 'El Paraíso'],
            [ 'municipio_id' => 387, 'nombre_localidad' => 'Andrés Linares'],
            [ 'municipio_id' => 387, 'nombre_localidad' => 'Chiquinquirá'],
            [ 'municipio_id' => 387, 'nombre_localidad' => 'Cristóbal Mendoza'],
            [ 'municipio_id' => 387, 'nombre_localidad' => 'Cruz Carrillo'],
            [ 'municipio_id' => 387, 'nombre_localidad' => 'Matriz'],
            [ 'municipio_id' => 387, 'nombre_localidad' => 'Monseñor Carrillo'],
            [ 'municipio_id' => 387, 'nombre_localidad' => 'Tres Esquinas'],
            [ 'municipio_id' => 388, 'nombre_localidad' => 'Cabimbú'],
            [ 'municipio_id' => 388, 'nombre_localidad' => 'Jajó'],
            [ 'municipio_id' => 388, 'nombre_localidad' => 'La Mesa de Esnujaque'],
            [ 'municipio_id' => 388, 'nombre_localidad' => 'Santiago'],
            [ 'municipio_id' => 388, 'nombre_localidad' => 'Tuñame'],
            [ 'municipio_id' => 388, 'nombre_localidad' => 'La Quebrada'],
            [ 'municipio_id' => 389, 'nombre_localidad' => 'Juan Ignacio Montilla'],
            [ 'municipio_id' => 389, 'nombre_localidad' => 'La Beatriz'],
            [ 'municipio_id' => 389, 'nombre_localidad' => 'La Puerta'],
            [ 'municipio_id' => 389, 'nombre_localidad' => 'Mendoza del Valle de Momboy'],
            [ 'municipio_id' => 389, 'nombre_localidad' => 'Mercedes Díaz'],
            [ 'municipio_id' => 389, 'nombre_localidad' => 'San Luis'],
            [ 'municipio_id' => 390, 'nombre_localidad' => 'Caraballeda'],
            [ 'municipio_id' => 390, 'nombre_localidad' => 'Carayaca'],
            [ 'municipio_id' => 390, 'nombre_localidad' => 'Carlos Soublette'],
            [ 'municipio_id' => 390, 'nombre_localidad' => 'Caruao'],
            [ 'municipio_id' => 390, 'nombre_localidad' => 'Catia La Mar'],
            [ 'municipio_id' => 390, 'nombre_localidad' => 'El Junko'],
            [ 'municipio_id' => 390, 'nombre_localidad' => 'La Guaira'],
            [ 'municipio_id' => 390, 'nombre_localidad' => 'Macuto'],
            [ 'municipio_id' => 390, 'nombre_localidad' => 'Maiquetía'],
            [ 'municipio_id' => 390, 'nombre_localidad' => 'Naiguatá'],
            [ 'municipio_id' => 390, 'nombre_localidad' => 'Urimare'],
            [ 'municipio_id' => 391, 'nombre_localidad' => 'Arístides Bastidas'],
            [ 'municipio_id' => 392, 'nombre_localidad' => 'Bolívar'],
            [ 'municipio_id' => 407, 'nombre_localidad' => 'Chivacoa'],
            [ 'municipio_id' => 407, 'nombre_localidad' => 'Campo Elías'],
            [ 'municipio_id' => 408, 'nombre_localidad' => 'Cocorote'],
            [ 'municipio_id' => 409, 'nombre_localidad' => 'Independencia'],
            [ 'municipio_id' => 410, 'nombre_localidad' => 'José Antonio Páez'],
            [ 'municipio_id' => 411, 'nombre_localidad' => 'La Trinidad'],
            [ 'municipio_id' => 412, 'nombre_localidad' => 'Manuel Monge'],
            [ 'municipio_id' => 413, 'nombre_localidad' => 'Salóm'],
            [ 'municipio_id' => 413, 'nombre_localidad' => 'Temerla'],
            [ 'municipio_id' => 413, 'nombre_localidad' => 'Nirgua'],
            [ 'municipio_id' => 414, 'nombre_localidad' => 'San Andrés'],
            [ 'municipio_id' => 414, 'nombre_localidad' => 'Yaritagua'],
            [ 'municipio_id' => 415, 'nombre_localidad' => 'San Javier'],
            [ 'municipio_id' => 415, 'nombre_localidad' => 'Albarico'],
            [ 'municipio_id' => 415, 'nombre_localidad' => 'San Felipe'],
            [ 'municipio_id' => 416, 'nombre_localidad' => 'Sucre'],
            [ 'municipio_id' => 417, 'nombre_localidad' => 'Urachiche'],
            [ 'municipio_id' => 418, 'nombre_localidad' => 'El Guayabo'],
            [ 'municipio_id' => 418, 'nombre_localidad' => 'Farriar'],
            [ 'municipio_id' => 441, 'nombre_localidad' => 'Isla de Toas'],
            [ 'municipio_id' => 441, 'nombre_localidad' => 'Monagas'],
            [ 'municipio_id' => 442, 'nombre_localidad' => 'San Timoteo'],
            [ 'municipio_id' => 442, 'nombre_localidad' => 'General Urdaneta'],
            [ 'municipio_id' => 442, 'nombre_localidad' => 'Libertador'],
            [ 'municipio_id' => 442, 'nombre_localidad' => 'Marcelino Briceño'],
            [ 'municipio_id' => 442, 'nombre_localidad' => 'Pueblo Nuevo'],
            [ 'municipio_id' => 442, 'nombre_localidad' => 'Manuel Guanipa Matos'],
            [ 'municipio_id' => 443, 'nombre_localidad' => 'Ambrosio'],
            [ 'municipio_id' => 443, 'nombre_localidad' => 'Carmen Herrera'],
            [ 'municipio_id' => 443, 'nombre_localidad' => 'La Rosa'],
            [ 'municipio_id' => 443, 'nombre_localidad' => 'Germán Ríos Linares'],
            [ 'municipio_id' => 443, 'nombre_localidad' => 'San Benito'],
            [ 'municipio_id' => 443, 'nombre_localidad' => 'Rómulo Betancourt'],
            [ 'municipio_id' => 443, 'nombre_localidad' => 'Jorge Hernández'],
            [ 'municipio_id' => 443, 'nombre_localidad' => 'Punta Gorda'],
            [ 'municipio_id' => 443, 'nombre_localidad' => 'Arístides Calvani'],
            [ 'municipio_id' => 444, 'nombre_localidad' => 'Encontrados'],
            [ 'municipio_id' => 444, 'nombre_localidad' => 'Udón Pérez'],
            [ 'municipio_id' => 445, 'nombre_localidad' => 'Moralito'],
            [ 'municipio_id' => 445, 'nombre_localidad' => 'San Carlos del Zulia'],
            [ 'municipio_id' => 445, 'nombre_localidad' => 'Santa Cruz del Zulia'],
            [ 'municipio_id' => 445, 'nombre_localidad' => 'Santa Bárbara'],
            [ 'municipio_id' => 445, 'nombre_localidad' => 'Urribarrí'],
            [ 'municipio_id' => 446, 'nombre_localidad' => 'Carlos Quevedo'],
            [ 'municipio_id' => 446, 'nombre_localidad' => 'Francisco Javier Pulgar'],
            [ 'municipio_id' => 446, 'nombre_localidad' => 'Simón Rodríguez'],
            [ 'municipio_id' => 446, 'nombre_localidad' => 'Guamo-Gavilanes'],
            [ 'municipio_id' => 448, 'nombre_localidad' => 'La Concepción'],
            [ 'municipio_id' => 448, 'nombre_localidad' => 'San José'],
            [ 'municipio_id' => 448, 'nombre_localidad' => 'Mariano Parra León'],
            [ 'municipio_id' => 448, 'nombre_localidad' => 'José Ramón Yépez'],
            [ 'municipio_id' => 449, 'nombre_localidad' => 'Jesús María Semprún'],
            [ 'municipio_id' => 449, 'nombre_localidad' => 'Barí'],
            [ 'municipio_id' => 450, 'nombre_localidad' => 'Concepción'],
            [ 'municipio_id' => 450, 'nombre_localidad' => 'Andrés Bello'],
            [ 'municipio_id' => 450, 'nombre_localidad' => 'Chiquinquirá'],
            [ 'municipio_id' => 450, 'nombre_localidad' => 'El Carmelo'],
            [ 'municipio_id' => 450, 'nombre_localidad' => 'Potreritos'],
            [ 'municipio_id' => 451, 'nombre_localidad' => 'Libertad'],
            [ 'municipio_id' => 451, 'nombre_localidad' => 'Alonso de Ojeda'],
            [ 'municipio_id' => 451, 'nombre_localidad' => 'Venezuela'],
            [ 'municipio_id' => 451, 'nombre_localidad' => 'Eleazar López Contreras'],
            [ 'municipio_id' => 451, 'nombre_localidad' => 'Campo Lara'],
            [ 'municipio_id' => 452, 'nombre_localidad' => 'Bartolomé de las Casas'],
            [ 'municipio_id' => 452, 'nombre_localidad' => 'Libertad'],
            [ 'municipio_id' => 452, 'nombre_localidad' => 'Río Negro'],
            [ 'municipio_id' => 452, 'nombre_localidad' => 'San José de Perijá'],
            [ 'municipio_id' => 453, 'nombre_localidad' => 'San Rafael'],
            [ 'municipio_id' => 453, 'nombre_localidad' => 'La Sierrita'],
            [ 'municipio_id' => 453, 'nombre_localidad' => 'Las Parcelas'],
            [ 'municipio_id' => 453, 'nombre_localidad' => 'Luis de Vicente'],
            [ 'municipio_id' => 453, 'nombre_localidad' => 'Monseñor Marcos Sergio Godoy'],
            [ 'municipio_id' => 453, 'nombre_localidad' => 'Ricaurte'],
            [ 'municipio_id' => 453, 'nombre_localidad' => 'Tamare'],
            [ 'municipio_id' => 454, 'nombre_localidad' => 'Antonio Borjas Romero'],
            [ 'municipio_id' => 454, 'nombre_localidad' => 'Bolívar'],
            [ 'municipio_id' => 454, 'nombre_localidad' => 'Cacique Mara'],
            [ 'municipio_id' => 454, 'nombre_localidad' => 'Carracciolo Parra Pérez'],
            [ 'municipio_id' => 454, 'nombre_localidad' => 'Cecilio Acosta'],
            [ 'municipio_id' => 454, 'nombre_localidad' => 'Cristo de Aranza'],
            [ 'municipio_id' => 454, 'nombre_localidad' => 'Coquivacoa'],
            [ 'municipio_id' => 454, 'nombre_localidad' => 'Chiquinquirá'],
            [ 'municipio_id' => 454, 'nombre_localidad' => 'Francisco Eugenio Bustamante'],
            [ 'municipio_id' => 454, 'nombre_localidad' => 'Idelfonzo Vásquez'],
            [ 'municipio_id' => 454, 'nombre_localidad' => 'Juana de Ávila'],
            [ 'municipio_id' => 454, 'nombre_localidad' => 'Luis Hurtado Higuera'],
            [ 'municipio_id' => 454, 'nombre_localidad' => 'Manuel Dagnino'],
            [ 'municipio_id' => 454, 'nombre_localidad' => 'Olegario Villalobos'],
            [ 'municipio_id' => 454, 'nombre_localidad' => 'Raúl Leoni'],
            [ 'municipio_id' => 454, 'nombre_localidad' => 'Santa Lucía'],
            [ 'municipio_id' => 454, 'nombre_localidad' => 'Venancio Pulgar'],
            [ 'municipio_id' => 454, 'nombre_localidad' => 'San Isidro'],
            [ 'municipio_id' => 455, 'nombre_localidad' => 'Altagracia'],
            [ 'municipio_id' => 455, 'nombre_localidad' => 'Faría'],
            [ 'municipio_id' => 455, 'nombre_localidad' => 'Ana María Campos'],
            [ 'municipio_id' => 455, 'nombre_localidad' => 'San Antonio'],
            [ 'municipio_id' => 455, 'nombre_localidad' => 'San José'],
            [ 'municipio_id' => 456, 'nombre_localidad' => 'Donaldo García'],
            [ 'municipio_id' => 456, 'nombre_localidad' => 'El Rosario'],
            [ 'municipio_id' => 456, 'nombre_localidad' => 'Sixto Zambrano'],
            [ 'municipio_id' => 457, 'nombre_localidad' => 'San Francisco'],
            [ 'municipio_id' => 457, 'nombre_localidad' => 'El Bajo'],
            [ 'municipio_id' => 457, 'nombre_localidad' => 'Domitila Flores'],
            [ 'municipio_id' => 457, 'nombre_localidad' => 'Francisco Ochoa'],
            [ 'municipio_id' => 457, 'nombre_localidad' => 'Los Cortijos'],
            [ 'municipio_id' => 457, 'nombre_localidad' => 'Marcial Hernández'],
            [ 'municipio_id' => 458, 'nombre_localidad' => 'Santa Rita'],
            [ 'municipio_id' => 458, 'nombre_localidad' => 'El Mene'],
            [ 'municipio_id' => 458, 'nombre_localidad' => 'Pedro Lucas Urribarrí'],
            [ 'municipio_id' => 458, 'nombre_localidad' => 'José Cenobio Urribarrí'],
            [ 'municipio_id' => 459, 'nombre_localidad' => 'Rafael Maria Baralt'],
            [ 'municipio_id' => 459, 'nombre_localidad' => 'Manuel Manrique'],
            [ 'municipio_id' => 459, 'nombre_localidad' => 'Rafael Urdaneta'],
            [ 'municipio_id' => 460, 'nombre_localidad' => 'Bobures'],
            [ 'municipio_id' => 460, 'nombre_localidad' => 'Gibraltar'],
            [ 'municipio_id' => 460, 'nombre_localidad' => 'Heras'],
            [ 'municipio_id' => 460, 'nombre_localidad' => 'Monseñor Arturo Álvarez'],
            [ 'municipio_id' => 460, 'nombre_localidad' => 'Rómulo Gallegos'],
            [ 'municipio_id' => 460, 'nombre_localidad' => 'El Batey'],
            [ 'municipio_id' => 461, 'nombre_localidad' => 'Rafael Urdaneta'],
            [ 'municipio_id' => 461, 'nombre_localidad' => 'La Victoria'],
            [ 'municipio_id' => 461, 'nombre_localidad' => 'Raúl Cuenca'],
            [ 'municipio_id' => 447, 'nombre_localidad' => 'Sinamaica'],
            [ 'municipio_id' => 447, 'nombre_localidad'=> 'Elías Sánchez Rubio', ],
            [ 'municipio_id' => 447, 'nombre_localidad'=> 'Guajira',],
            [ 'municipio_id' => 462, 'nombre_localidad'=> 'Altagracia',],
            [ 'municipio_id' => 462, 'nombre_localidad'=> 'Antímano', ],
            [ 'municipio_id' => 462, 'nombre_localidad'=> 'Caricuao', ],
            [ 'municipio_id' => 462, 'nombre_localidad'=> 'Catedral', ],
            [ 'municipio_id' => 462, 'nombre_localidad'=> 'Coche', ],
            [ 'municipio_id' => 462, 'nombre_localidad'=> 'El Junquito', ],
            [ 'municipio_id' => 462, 'nombre_localidad'=> 'El Paraíso', ],
            [ 'municipio_id' => 462, 'nombre_localidad'=> 'El Recreo', ],
            [ 'municipio_id' => 462, 'nombre_localidad'=> 'El Valle', ],
            [ 'municipio_id' => 462, 'nombre_localidad'=> 'La Candelaria',],
            [ 'municipio_id' => 462, 'nombre_localidad'=> 'La Pastora', ],
            [ 'municipio_id' => 462, 'nombre_localidad'=> 'La Vega', ],
            [ 'municipio_id' => 462, 'nombre_localidad'=> 'Macarao', ],
            [ 'municipio_id' => 462, 'nombre_localidad'=> 'San Agustín', ],
            [ 'municipio_id' => 462, 'nombre_localidad'=> 'San Bernardino', ],
            [ 'municipio_id' => 462, 'nombre_localidad'=> 'San José', ],
            [ 'municipio_id' => 462, 'nombre_localidad'=> 'San Juan', ],
            [ 'municipio_id' => 462, 'nombre_localidad'=> 'San Pedro', ],
            [ 'municipio_id' => 462, 'nombre_localidad'=> 'Santa Rosalía',],
            [ 'municipio_id' => 462, 'nombre_localidad'=> 'Santa Teresa', ],
            [ 'municipio_id' => 462, 'nombre_localidad'=> 'Sucre (Catia)',],
            [ 'municipio_id' => 462, 'nombre_localidad'=> '23 de enero', ], 
        
        ];
        $this->command->info('Localidades insertadas correctamente.');

        
    

        foreach ($localidades as $localidad) {
            DB::table('localidads')->insert([
                'municipio_id' => $localidad['municipio_id'],
                'nombre_localidad' => $localidad['nombre_localidad'],
                'status' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
